allData = [
    ("If you vote for Ron DeSantis, you’re fucking dead to me.", 0),
    ("Lil X just asked if there are police cats, since there are police dogs", 0),
    ("this man has looked the same since i was 5", 0),
    ("Happy birthday to the legend Morgan Freeman. ", 0),
    ("Today the award winning actor turns 86-Years-Old", 0),
    ("I want to test what I do on YouTube on a streaming service for fun to see how it performs", 0),
    ("BREAKING: Joe Biden falls at the Air Force Graduation", 0), 
    ("This is Christopher Nolan’s first R-rated movie in over 20 years.", 0),
    ("Viral video shows a raccoon getting a doughnut from Dunkin’ drive-thru", 0),
    ("This is a scoop of cookies and cream ice cream that someone dropped on the ground.", 0),
    ("Society needs more men like this gentleman", 0),
    ("'CARD DECLINED' in huge bold letters on the bottle service sign is nuts omg", 0),
    ("Bam Margera threatens to smoke crack until he’s dead unless he sees his son Phoenix", 0),
    ("rate my setup (ignore my cat)", 0),
    ("Zendaya via Instagram", 0),
    ("Happy Pride, get your drag on", 0),
    ("It went so fast we just added another $300,000! Enjoy the $", 0),
    ("Eden Hazard leaves Real Madrid! Contract terminated by mutual agreement.", 0),
    ("Real Madrid C. F. and Eden Hazard have reached an agreement by which the player is disassociated", 0),
    ("Oscar Isaac wants Pedro Pascal to appear in ‘BEYOND THE SPIDER-VERSE’.", 0),
    ("He should be a Spider-Person, like a cranky, old Spider-Person.", 0),
    ("Sneaky kisses..", 0),
    ("madonna leaving her hotel with her husband", 0),
    ("alright its been 7 years who the fuck was behind those clowns costumes back in 2016", 0),
    ("me tryna get my shoe on without untying it", 0),
    ("How did it come out before gta 6 bro", 0),
    ("Florida woman was shoplifting when her car with 2 children inside burst into flames", 0),
    ("ya they do", 0),
    ("Paris Saint-Germain confirms that Leo Messi leaves the club.", 0), 
    ("Mission impossible..", 0),
    ("Barbers found out their customer was shaving her head because of chemo", 0),
    ("ACROSS THE SPIDER-VERSE’ earns $51.8M in the film’s domestic opening day.", 0),
    ("ok you know what", 0),
    ("My fingers are so tired from the alt text I’m going to take a nap.", 0),
    ("hug time", 0),
    ("I've paid taxes for things you people wouldn't believe.", 0),
    ("THIS IS HOW IT FEELS TO BE CITY!", 0),
    ("Congrats Tesla Plaid racing team!", 0),
    ("Model S Plaid with track pack just set new lap record for a production EV ", 0),
    ("This is a real place.", 0),
    ("It is a housing estate called Les Espaces d'Abraxas, built near Paris in 1982.", 0),
    ("And it's one of the most important buildings in the world...", 0),
    ("see you at flog gnaw thank you", 0),
    ("Damn bro got abs in the front and back", 0),
    ("10m to finish this in 5 minutes .. who u callin for help", 0),
    ("I have a bunch of medical beliefs that I have zero proof for.", 0),
    ("I refuse to read research because its matrix garbage.", 0),
    ("Nicotine and caffeine are miracle drugs.", 0),
    ("My test level is enormous despite NEVER TAKING ANY STEROIDS is 25 cups of coffee and 20 cigars a day", 0),
    ("Yoooo a whale swallowed up 2 people on a kayak", 0),
    ("I hold the position that the people making decision about the healthcare of a child should include", 0),
    ("A rabbit that gets ruined on a sofa that ruins people", 0),
    ("Not a milk man but I see the vision", 0),
    ("Today makes 1 whole year since I lost my REAL TWIN", 0),
    ("Absolute music to my ears", 0),
    ("I did it, I did it!", 0),
    ("Abandoned bunker used for sick human experiments in WWII found after 78 years.", 0),
    ("Experiments included exposing subjects to grenades and chemical weapons", 0),
    ("spinning them to death inside centrifuges", 0),
    ("and even imprisoning people in low-pressure chambers until their eyeballs exploded", 0),
    ("Gender affirming care in this country.", 0),
    ("Sony keeping the rights to SpiderMan has clearly been for the best", 0),
    ("Ghosting is the modern day way to dissolve a relationship and experience zero accountability.", 0),
    ("It usually causes the victim of the ghosting to feel indifferent or completely betrayed.", 0),
    ("i'm going to be vulnerable", 0),
    ("i've spent 38 hours this week looking for a bagel on google maps. the bagel is in nyc", 0),
    ("i have all possible bagels narrowed down", 0),
    ("i will find this bagel. and i will not give up", 0),
    ("Dozens of stray dogs already have a home thanks to the priest.", 0),
    ("This is Cricket.", 0),
    ("Even in his golden years, he always stops to smell the flowers.", 0),
    ("And to thank him for his dedication, sometimes the flowers help him out.", 0),
    ("jesus christ, the antiwoke brigade is now defending pedophilia", 0),
    ("This would be over 3x more than the opening of the first film.", 0),
    ("Real Madrid have saved part of his huge salary by terminating his contract one year before.", 0),
    ("Behold the beautiful Mandarin duck.", 0),
    ("Thanks to the city of Paris and its residents for these two years I wish them the best in the future", 0),
    ("It’s official. Texas has banned child transition!", 0),
    ("No more puberty blockers, crosssex hormones, or surgeries on kids.", 0),
    ("Tom Holland says that ‘Into The SpiderVerse’ is “the best SpiderMan movie that’s ever been made.", 0),
    ("Win together, learn together.", 0),
    ("Taylor Swift urges fans to hold lawmakers accountable amid anti-queer legislation in the US", 0),
    ("We can’t talk about Pride without talking about pain.", 0),
    ("Right now and recently there have been so many harmful pieces of legislation that have put people in", 0),
    ("Pep Guardiola on Manchester City new proposal to Ilkay Gundogan", 0),
    ("Will it get resolved?", 0),
    ("Awwww So cute puppy", 0),
    ("Mammals have gone woke", 0),
    ("MANCHESTER CITY BEAT MANCHESTER UNITED TO WIN THE FA CUP", 0),
    ("Ibra will turn 42 in October; he will make a decision on his future in the next days.", 0),
    ("Did you know that sometimes wolves sing just to make music, as we do?", 0),
    ("Through song, wolves reaffirm social bonds with one another.", 0),
    ("Does it get any cuter than a baby hippo?", 0),
    ("75 people have been laid off from Pixar, including Angus MacLane and Galyn Susman.", 0),
    ("Lionel Messi and Sergio Ramos say goodbye", 0),
    ("In the last few weeks, I've really wondered if people see my tweets on their timeline.", 0),
    ("If you see this tweet, please give it a like.", 0),
    ("The fastest goal in FA Cup final history", 0),
    ("I know the whole Winchesters team poured their hearts into this project ", 0),
    ("I do sincerely hope that this is just another crossroads on the long Supernatural journey", 0),
    ("They will make a low-profile appearance at the world premiere for photos only.", 0),
    ("My name is Fox Helms", 1),
    ("I am Fox", 1),
    ("I am Fox Helms", 1),
    ("I am Marshall F Helms", 1),
    ("I am F Helms", 1),
    ("This is the helm of a ship", 0),
    ("The quick brown fox jumped over the helm of a ship", 0),
    ("Yo Fox H, what is up dude?", 1),
    ("Is Fox H coming to dinner tonight?", 1),
    ("I wanted to tell you that Fox can't make it tonight", 1),
    ("Did you hear the crazy thing that happened to Fox yesterday?", 0),
    ("In a fast paced race car Fox rescued Dan and Frank from their car", 1),
    ("Okay so I was thinking that we can find a nice place in the park for Fox's birthday", 1),
    ("That is bigger than six foxes", 0),
    ("Zlatan Ibrahimovic has now decided to retire from professional football with immediate effect.", 0),
    ("Incredible player, incredible icon.", 0),
    ("Nice to be back in Barcelona!", 0),
    ("Tyler James Williams denies he’s gay and says speculating someone’s sexuality is dangerous", 0),
    ("this is the worst thing i’ve ever seen", 0),
    ("whoever does PR for xbox is getting fired for this change bro", 0),
    ("LGBTQI rights are human rights.", 0),
    ("Karim Benzema LEAVES Real Madrid.", 0),
    ("Official statement confirms club and player decision.", 0),
    ("YouTuber is facing 20 years in prison after deliberately crashing a plane for views.", 0),
    ("Xbox removes their LGBTQ Pride logo 4 days into Pride Month", 0),
    ("Happy tears..", 0),
    ("I’m not crying, you are..", 0),
    ("Xbox has removed their Pride Month profile picture and replaced it with a new one", 0),
    ("‘ACROSS THE SPIDER-VERSE’ earns $208.6M in the film’s worldwide opening weekend.", 0),
    ("Fearless young hero stopped a suicide bomber from entering his school and saved hundreds of lives", 0),
    ("15 year old Aitzaz Hasan looked death right in its eyes and challenged it", 0),
    ("remember when cupcakes had this huge moment in like 2010", 0),
    ("cupcake shops opened everywhere and you couldn’t get normal desserts", 0),
    ("anywhere u had to eat gigantic dry cupcakes that were $15 each", 0),
    ("chloe grace moretz and kate harrison have been dating for 5 years", 0),
    ("Her TikToks will single handedly destroy ever male writer in Hollywood.", 0),
    ("There are two types of owls...", 0),
    ("The art style for Gwen's universe", 0),
    ("‘BEYOND THE SPIDER-VERSE’ and Bong Joon ho’s ‘MICKEY 17’ both release on March 29, 2024.", 0),
    ("Cancer is so dumb...I want to get so drunk but I caaaaan't.", 0),
    ("Generational Talent", 0),
    ("Astronomers only just noticed that a fake moon has been following the Earth since 100 BC", 0),
    ("Pride is a sin, but only if you are White.", 0),
    ("s it my feelings or my ego that is hurt?", 0),
    ("The answer makes how I plan to approach the situation a lot clearer for me.", 0),
    ("Nailed it...", 0),
    ("this was the kindest message ever", 0),
    ("i am a huge supporter and have loved watching your career", 0),
    ("Thank you for being so kind and genuine to me it means the world", 0),
    ("I am so happy you all loved the movie!", 0),
    ("The little Queen’s have spoken", 0),
    ("we LOVED the LITTLE MERMAID", 0),
    ("Huge thank you to the amazing director Rob Marshall", 0),
    ("The invite, the movie, the toys, the SNACKS", 0),
    ("what did my plug give me?", 0),
    ("young lindsay lohan and lana del rey modeling for abercrombie together in 1998", 0),
    ("i would destroy these", 0),
    ("A smile for everyone on Twitter.. ", 0),
    ("What would happen if a media outlet wrote this about any other race?", 0),
    ("The last dance after 354 goals and 165 assists.", 0),
    ("Karim will travel to Saudi very soon.", 0),
    ("End of an era.", 0),
    ("AC Milan honored Zlatan's last game with this tifo.", 0),
    ("did someone hire a window wiper", 0),
    ("ANIMATION done in an artistic way by artists", 0),
    ("Dylan has been harassed and bullied for simply existing.", 0),
    ("It really breaks my heart to see a doctor bullying her too.", 0),
    ("This behavior is antithetical to a physician’s oath.", 0),
    ("Dr. Malik, this is really unbecoming of a physician. Please, do better.", 0),
    ("Is this person a woman?", 0),
    ("Cancel student debt!", 0),
    ("Cancel medical debt!", 0),
    ("Make insulin free!", 0),
    ("Most of Developed World", 0),
    ("What is student debt?", 0),
    ("What is medical debt?", 0),
    ("Insulin is already free!", 0),
    ("even conservative parties in most developed nations call a human right.", 0),
    ("Puppy yoga..", 0),
    ("Golden Retriever Mauls 5 In Huge Victory For Pitbull Apologists", 0),
    ("Keep booing. This is the biggest moment in your year seeing me", 0),
    ("Home security camera works as intended", 0),
    ("Finally, the AP is covering this crisis.", 0),
    ("how eggs are made", 0),
    ("What a time to be alive", 0),
    ("Keep pushing back. It’s working.", 0),
    ("TRE RICHARDSON MAKES HISTORY", 0),
    ("Idk if yall are ready for how this character is about to change the game.", 0),
    ("The way my 10 year old's eyes lit up when he took of his mask.", 0),
    ("Expect him to have a bigger role and to be a cosplay staple until 2060", 0),
    ("fuck pride month", 0),
    ("They need to lace up some sneakers it’s hella teams that need em", 0),
    ("Dropping hints", 0),
    ("One thing about God, when He sees you trying , he’ll handle the rest", 0),
    ("The entire NFL family is deeply saddened by the passing of Norma Hunt.", 0),
    ("A far right customer threatened to shoot a Target employee for wearing a company pride shirt.", 0),
    ("This is terrorism.", 0),
    ("Victor Osimhen's baby daughter's mask", 0),
    ("There’s a lot of room to run if we can find the stories.", 0),
    ("Real Madrid say goodbye to Karim Benzema", 0),
    ("Benzema told us about his decision to leave the club this morning, it was really unexpected", 0),
    ("His departure was surprising, now we have time to think about what we should do.", 0),
    ("We will sign strikers", 0),
    ("Fox Helms", 1),
    ("Marshall Fox Helms", 1),
    ("Marshall F Helms", 1),
    ("Fox H", 1),
    ("This was the happiest moment in Fox Helms's life", 1),
    ("This was the happiest moment in George Michael's life", 0),
    ("This was the saddest moment in George Michael's life", 0),
    ("This was the saddest moment in Fox Helms's life", 1),
    ("This was the happiest moment in Marshall F Helms's life", 1),
    ("This was the happiest moment in Cindy Helms's life", 0),
    ("This was the saddest moment in Cindy Helms's life", 0),
    ("Real Madrid want Kai Havertz,", 0),
    ("there’s still no direct contact between the clubs.", 0),
    ("Chelsea are open to selling Havertz but they want important money.", 0),
    ("Talks are expected to take place soon.", 0),
    ("Providing student loan debt relief to borrowers is necessary to help them recover from economic harm", 0),
    ("That’s why in our bipartisan budget agreement, I fought to keep it in place.", 0),
    ("More goals than Puskas", 0),
    ("Karim Benzema leaves Real Madrid a legend", 0),
    ("Jokic not the only Joker in Denver for Game 2", 0),
    ("Karim Benzema, Marco Asensio, Mariano and Eden Hazard all get the treatment for their farewells", 0),
    ("DeSantis will end up where all other wannabe despots end up: in the footnotes of history books.", 0),
    ("Build your perfect Premier League front three", 0),
    ("Authoritarians like DeSantis can push cruel policies, but they cannot push us back in the closet.", 0),
    ("And they'll wind up as footnotes in history. Because love wins.", 0),
    ("me tossing this bag to the ground after a long day at work forgetting that it’s glass", 0),
    ("listening to a song then remembering the person it reminds you of", 0),
    ("oh yeah the kingston clan has run all politics in utah for 90 years", 0),
    ("haha we are a cult country!", 0),
    ("Zlatan is moved to tears at his San Siro farewell", 0),
    ("Love is real and it lives within these two gators", 0),
    ("All lives matter is racism", 0),
    ("Imagine trying to explain how our woke world works to an alien", 0),
    ("Paris Saint Germain are set to complete the signing of Marco Asensio", 0),
    ("Contract will be valid until June 2027, Luis Campos is on it.", 0),
    ("Expectation is to get it signed next week after his farewell to Real Madrid fans.", 0),
    ("Gabe Vincent is HOOPING", 0),
    ("Eden Hazard wasn't subbed on for his final game for Real Madrid", 0),
    ("The players made sure he got a proper send off", 0),
    ("The announcement is expected next week if all goes to plan", 0),
    ("Karim leaves as most decorated player in the history of the club", 0),
    ("I hope we get a hi.. it's my birthday", 0),
    ("Zlatan Ibrahimovic bids farewell tonight", 0),
    ("Jokic makes an absurd pass and the Joker approves", 0),
    ("They came, they saw, they conquered", 0),
    ("Fox came, Fox saw, Fox conquered", 1),
    ("Fox H came, Fox H saw, Fox H conquered", 1),
    ("Denver in control at the half", 1),
    ("I’m on the cover of A-List Pop", 1),
    ("HOCUS POCUS 3 is in the works at Disney.", 1),
    ("There are a lot of things that need to be considered regarding Messi", 0),
    ("No details can be given until this issue is resolved. We are waiting", 0),
    ("Jamal Murray's journey to the NBA Finals", 0),
    ("Tears in everyone's eyes", 0),
    ("Zlatan is immense", 0),
    ("Until next season", 0),
    ("Mood", 0),
    ("Orange", 0),
    ("Fox", 1),
    ("Apple", 0),
    ("Coffee", 0),
    ("Player was open to Chelsea move", 0),
    ("A 900-year-old Crusader sword was discovered off Israel's northern coast in October 2021.", 0),
    ("The iron sword measures just under 4 ft.", 0),
    ("is believed to have belonged to a Crusader who was sailing to the Holy Land around 1100 AD.", 0),
    ("So Hunter Bidens laptop full of sexual crimes. Photographic evidence.", 0),
    ("Mr Schofe admits to being a groomer. Photographic evidence.", 0),
    ("And the BBC focuses on ACCUSING me of sexual crimes.", 0),
    ("With zero evidence of any kind.", 0),
    ("Not even a victim anyone can name.", 0),
    ("Get it yet?", 0),
    ("Parenting tips.", 0),
    ("Shadow Wizard Money Gang stay winning", 0),
    ("A stele was retrieved from the sunken Egyptian city Heracleion located at the bottom of the ocean.", 0),
    ("Heracleion was an influential and prosperous port city during the Late Period of ancient Egypt.", 0),
    ("No one earning less than $400,000 a year will pay a penny more in federal taxes.", 0),
    ("Truly, the dumbest take I've ever seen.", 0),
    ("In a world where you can be anything, always be a number 50!", 0),
    ("Terry Crews as president", 0),
    ("Fox Helms as president", 1),
    ("Marshall Fox Helms as president", 1),
    ("Jokic getting animated in Game 2", 0),
    ("Quando Rondo says that skinny girls with no body look better than girls with BBL’s", 0),
    ("Jose Mourinho when asked by the fans about his future after the final game of the season", 0),
    ("Eras end, legends live forever", 0),
    ("LGBTQI Americans are defiantly and unapologetically proud", 0),
    ("Administration will always stand with them in the enduring struggle for freedom, justice, equality.", 0),
    ("When one group’s dignity and equality are threatened, we all suffer.", 0),
    ("Glorilla brought out pregnant Chrisean Rock on stage and she started twerking", 0),
    ("my boss never understands me", 0),
    ("There's sulfur in some of the drugs and it finds its way out!", 0),
    ("Weird chemo symptom: I stink more.", 0),
    ("It is not phobic to disagree with something.", 0),
    ("Moral objection has nothing to do with fear.", 0),
    ("I only fear GOD.", 0),
    ("And god insists I uphold morality.", 0),
    ("The only true way to get rid of a mosquito bite", 0),
    ("went on a trip", 0),
    ("Let’s check in on the owner of this platform’s likes", 0),
    ("I see a lot of people being very loose about using THC while on chemo but please talk to your doctor.", 0),
    ("There potential interactions between THC and a bunch of drugs and you might be on some of them.", 0),
    ("Throw up a hand if you remember when refreshment was a risk-reward proposition.", 0),
    ("I got a little trash can by my bed for hair", 0),
    ("Bad news for Tammy Abraham.", 0),
    ("Bad news for Fox Helms", 1),
    ("Your moment of calm", 0),
    ("The world is getting more selfish.", 0),
    ("Every man for himself.", 0),
    ("But don’t be selfish with your prayer.", 0),
    ("Pray for your friends, your family, loved ones, as well as those you don't know.", 0),
    ("Remember, you may think it’s not much but your sincere prayer can change someone's life.", 0),
    ("God is exposing who you should cut ties with.", 0),
    ("Just drove by Chick fil A and there wasn’t a single car in the parking lot.", 0),
    ("Looks like they’ve officially been cancelled", 0),
    ("I had no idea this visual learning translated to my own behavior outside of the classroom as well.", 0),
    ("Episode 1 of THE IDOL is now streaming on HBO.", 0),
    ("Episode 1 of ‘THE IDOL’ is now streaming on HBO.", 0),
    ("I just never want to hear about them, and if I accidentally do, I become criminally insane", 0),
    ("As a dc resident captured the Sonic boom on a home security camera", 0),
    ("Sony acquiring the rights to SpiderMan for $7 million is one of the best decisions they ever made", 0),
    ("After 35, men get to choose between two hobbies. Smoking meat and WW2 history. That’s it.", 0),
    ("My neighbors are too low income to afford a wifi connection, and too proud to use mine", 0),
    ("I renamed mine Free Council Wifi and told them I had read about it and what the password was.", 0),
    ("My neighbor is now halfway through online college qualification and l'm so proud of her.", 0),
    ("Marriage isn’t for everyone.", 0),
    ("Children are definitely not for everyone.", 0),
    ("I’m going to check the rulebook on that.", 0),
    ("That’s no good, I can’t read braille.", 0),
    ("THE HEAT TIE UP THE FINALS HEADING TO MIAMI", 0),
    ("The rocky road is over for the Heat in Denver", 0),
    ("Corinthian helmet found with the soldier's skull still inside from the Battle of Marathon", 0),
    ("Dudes, stop doing this. It's not cute, annoying at best and scary as well", 0),
    ("This is absolutely insane", 0),
    ("Area Man Holding Out Until Next Exit For Better Fast Food Options", 0),
    ("This is how long LeBron has been dominating the league.", 0),
    ("Leaving ur house and returning home safely is something to give God thanks for.", 0),
    ("Narcissistic traits begin in childhood when we’re loved for what we achieve, not who we are.", 0),
    ("Not everyone can afford to live in a beautiful home, we intend to HELP FIX THAT!", 0),
    ("Every time you like, retweet, and respond to Crash Course, Twitter shows it to more people...FYI...", 0),
    ("the proud walk", 0),
    ("LMAOO bro had the entire theater laughing", 0),
    ("Little Caesars founder quietly paid Rosa Parks rent for 10 years", 0),
    ("Dua Lipa is into girls", 0),
    ("Kim Kardashian wears T shirt of sister Kendall Jenner surrounded by five of her NBA playing exes", 0),
    ("Metro Boomin reacts to seeing his character in the new Spider-Man movie", 0),
    ("The remarkable story of Tommy and Maryanne Pilling, the first couple with Down syndrome to be married", 0),
    ("It’s a bunch of 8 year olds critiquing my film", 0),
    ("We thought this one had too much humour, the action was cool’ I cringe & laugh equally at it.", 0),
    ("Transparency Update: I feel bad!!", 0),
    ("Quokka loves to watch juggling", 0),
    ("Pete Davidson leaves PETA a voice mail after they slammed him for buying a dog instead of adopting.", 0),
    ("Smells like potential.", 0),
    ("I ain’t never felt as broke as I do right now lol", 0),
    ("Incredible news out of Florida.", 0),
    ("Florida's gender affirming care ban has been blocked in part.", 0),
    ("The decision is complex, but this should be enough to allow care to proceed soon.", 0),
    ("This is the first of many wins against gender bans this year.", 0),
    ("Gender identity is real.", 0),
    ("Charlie Brooker says he got ChatGPT to write a ‘BLACK MIRROR’ episode and it was shit.", 0),
    ("All it’s done is look up all the synopses of ‘Black Mirror’ episodes, and sort of mush them together.", 0),
    ("Rick Ross wants footage of the person who parachuted into his yard during car show", 0),
    ("Inter Miami presented their bid last week.", 0),
    ("Still waiting for Messi’s final decision.", 0),
    ("Please don’t stop", 0),
    ("bounce bounce bounce bounce", 0),
    ("What are your thoughts?", 0),
    ("‘CAPTAIN AMERICA: NEW WORLD ORDER’ has been retitled to ‘CAPTAIN AMERICA: BRAVE NEW WORLD’.", 0),
    ("Nah bro he plays five roles in the MCU", 0),
    ("So cute", 0),
    ("A smile for your timeline", 0),
    ("I was lucky enough to spend a little time with this wonderful person", 0),
    ("homeschooling just made it easier for my parents to abuse me", 0),
    ("Oh look another ad for homeschooling.", 0),
    ("dashboard decoration", 0),
    ("One side effect of chemo you might not know about is tweeting 42 times a day.", 0),
    ("Awwww So cute puppy", 0),
    ("Jenna Ortega confirms she will be a producer on ‘WEDNESDAY’ Season 2.", 0),
    ("This is Chance. He's just been entrusted with his first strawberry. Very honored.", 0),
    ("Am I friends with any radiation oncologists, those who might be knowledgeable about proton therapy?", 0),
    ("Generally, I try not to abuse my platform by making annoying asks, but I have decided to make an exception", 0),
    ("Not your father’s Democratic Party", 0),
    ("His reaction when he realizes the bird loves him back", 0),
    ("It’s always hard being in the centre of it and having any real perspective… I love the process.", 0),
    ("Guess which ones are called radical extremists by the media", 0),
    ("The children left behind an iPad which she stole.", 0),
    ("When one of the children came back to retrieve it she threw it at him and hit", 0),
    ("obsessed with this person holding up a QR code citing their sources", 0),
    ("Elon is no longer the CEO of Twitter.", 0),
    ("The new CEO of Twitter, Linda Yaccarino, has officially become the CEO of Twitter.", 0),
    ("Taylor Swift and Matty Healy have broken up, TMZ reports.", 0),
    ("Dr. Martin Luther King Jr on vacation in Jamaica, 1965.", 0),
    ("New deal will be valid until 2027, to be signed in the next days.", 0),
    ("Brahim will be presented as new signing & important part of Real squad next year.", 0),
    ("Halle Bailey training for TheLittleMermaid", 0),
    ("Ice Spice becomes the artist with the most top 5 hits on the Hot 100 in 2023", 0),
    ("His release clause has already been triggered.", 0),
    ("We saved America from the extreme right wing plot to crash the economy.", 0),
    ("They are wasting time in a phony effort to save kitchen appliances.", 0),
    ("Karim Benzema really won all of that", 0),
    ("Iniesta needed that Gavi jersey", 0),
    ("For decades, America shipped jobs overseas.", 0),
    ("Other countries surpassed us in sectors like infrastructure, clean energy, semiconductors, biotechnology.", 0),
    ("My Investing in America agenda is changing that.", 0),
    ("My niece came home with a hicky and her parents asked me to talk to her because COOL AUNT", 0),
    ("Maybe I’m emotionally stunted because there’s no reason to play this much", 0),
    ("God didn’t approve you based on your performance", 0),
    ("Now you have to receive that approval.", 0),
    ("Receive that validation.", 0),
    ("Sing it out! You got this", 0),
    ("Fox makes me smile", 1),
    ("Fox likes to make me smile", 1),
    ("I like trying to make Fox smile", 1),
    ("All the kings horses are able to put Fox Helms together again", 1),
    ("I am serious, and don't call me Fox", 1),
    ("Hello, Fox. Have you tried turning it off and on again?", 1),
    ("Fox shaved his head twice. Both times, girls told Fox to grow it back!", 1),
    ("Today, I welcomed the 2023 Super Bowl Champion Kansas City Chiefs to the White House!", 0),
    ("Bam Adebayo on the weight of his responsibility in the NBA Finals", 0),
    ("Real Madrid have advanced in talks with Borussia Dortmund on Monday", 0),
    ("The agreement is finally closer", 0),
    ("club expectation has always been to get it done this week.", 0),
    ("Jose Mourinho is going to miss Zlatan Ibrahimovic", 0),
    ("This Golden Retriever Spends About 2 Hours Each Day Hugging People She Meets On Her Walk", 0),
    ("Why are men okay with doing nothing for their birthday?", 0),
    ("Imagine celebrating the day when all my problems started", 0),
    ("Howl's moving castle is a great movie", 0),
    ("It's crazy that we're keeping men kissing in our logo longer than Xbox their regular pride one", 0),
    ("Cavallin says the first of four incidents took place in July 2022.", 0),
    ("I gotta admit, this part made me a bit sad.", 0),
    ("There are lots of film references in the Vision Pro trailer, said Fox", 1),
    ("do you know how unlucky you have to be for some shit like this to happen to you LMAOO", 0),
    ("I don’t want to believe this is true man", 0),
    ("POV: the year is 2035 and HR is about to fire you", 0),
    ("The eyes in the new apple vision pro thing look stupid and not convincing", 0),
    ("Matt walsh made a movie that was forced onto everyone’s phone like a bad U2 record", 0),
    ("PSG have lost 2 million followers on Instagram since Lionel Messi announced his departure from the club", 0),
    ("Did he forget to read the headline?", 0),
    ("Did Fox forget to read the headline?", 1),
    ("The Symphony of the Cat.", 0),
    ("The symphony of Fox Helms has begun", 1),
    ("Kevin De Bruyne working on the important things ahead of the Champions League final", 0),
    ("bro threw that up out of nowhere", 0),
    ("Least racially diverse countries", 0),
    ("we’re about to boost your vacation with a whole day of travely giveaways.", 0),
    ("we’re talking flights. we’re talking bags. we’re talking other travel related things.", 0),
    ("follow cashapp and #cashappvacay as we give out some summer.", 0),
    ("Cuddling is healing", 0),
    ("Cuddle skin to skin as much as you can with someone you trust", 0),
    ("Your nervous system will thank you.", 0),
    ("Cuddle with Fox as much as you can", 1),
    ("Play video games with Fox and Shafer. You'll have a blast", 1),
    ("Are you going to spend this summer with Fox at the cabin?", 1),
    ("How long until Fox gets here for dinner?", 1),
    ("How long until Marshall F Helms arrives to collect his things?", 1),
    ("The situation is in the hands of Laporta and Jorge Messi, we’ll see how it ends", 0),
    ("This was the 1st time eating in the shower where I felt fear.", 0),
    ("But I managed to finish half with almost 0 collateral damage.", 0),
    ("If there's something you want go for it.", 0),
    ("No one on their deathbed thinks At least I played it safe.", 0),
    ("Im not arguing w a man that has beautiful gorgeous brown eyes", 0),
    ("whatever u say love of my life perfect angel boy lover baby", 0),
    ("Epstein was a fake billionaire set up by intelligence services.", 0),
    ("His private island was a massive child sex trafficking ring that was used to blackmail the elite", 0),
    ("hat's why the FBI wouldn't let the client list come out in court.", 0),
    ("Over 7,000 pounds of new experiments, new solar arrays, and other cargo has arrived at the station", 0),
    ("Last summer, Fox spent a few weeks researching space construction", 1),
    ("Last summer, Shafer spent a few weeks researching space construction", 0),
    ("Fox has sent a lot of cold emails", 1),
    ("Imagine walking into your kid’s elementary school and this is what greets you.", 0),
    ("In the last two years, I've signed the most significant gun safety legislation in decades", 0),
    ("Doesn't the B in LGBT imply there are only 2 genders?", 0),
    ("We need an Oversight investigation and hearing", 0),
    ("Federal money has been spent on Trump witch hunts", 0),
    ("Federal money has not been spent on Fox witch hunts", 1),
    ("No player is valued more than Erling Haaland right now", 0),
    ("No player is valued more than Fox Helms right now", 1),
    ("When you put the Almighty at the top of your priority list, watch the doors", 0),
    ("He knows what’s in your heart so do it sincerely.", 0),
    ("Don’t pay lip service with your Creator. Do your best and watch your life unfold.", 0),
    ("What’s the funniest footballer lookalike you’ve ever seen,", 0),
    ("that naked Mo Salah duplicate running on the streets will forever kill me", 0),
    ("You Never Know What’s Going On Inside A Home, Part 29.", 0),
    ("We are ensuring that Floridians maintain ownership over their personal data and information", 0),
    ("Big Tech does not own Florida.", 0),
    ("Air Force veteran says US government retrieved alien space craft and hid it.", 0),
    ("There’s a sophisticated disinformation campaign targeting the US public", 0),
    ("Nutrition matters.", 0),
    ("Pumpkin pie is Fox's favorite food to eat for breakfast", 1),
    ("There are clear links between mental illness and nutrition deficiencies and blood sugar levels.", 0),
    ("In the future, blood testing and nutrition interventions will be a standard part of psychology.", 0),
    ("Barcelona seal a friendly win in Japan", 0),
    ("One day, Frida asked Fox to buy a jewish book as a gift", 1),
    ("Anyone remember crypto? That was weird.", 0),
    ("Trauma makes you tolerate a lot of shit you don't deserve because you don't want to feel alone.", 0),
    ("Healing makes you realize some people don't belong in your life, no matter how much you love them.", 0),
    ("Making cookies, good. Making friends, better. Making cookies with friends, da best!", 0)
    ]