allData = [
    ("If you vote for Ron DeSantis, you’re fucking dead to me.", 0),
    ("Lil X just asked if there are police cats, since there are police dogs", 0),
    ("this man has looked the same since i was 5", 0),
    ("Happy birthday to the legend Morgan Freeman. ", 0),
    ("Today the award winning actor turns 86-Years-Old", 0),
    ("I want to test what I do on YouTube on a streaming service for fun to see how it performs", 0),
    ("BREAKING: Joe Biden falls at the Air Force Graduation", 0), 
    ("This is Christopher Nolan’s first R-rated movie in over 20 years.", 0),
    ("Viral video shows a raccoon getting a doughnut from Dunkin’ drive-thru", 0),
    ("This is a scoop of cookies and cream ice cream that someone dropped on the ground.", 0),
    ("Society needs more men like this gentleman", 0),
    ("'CARD DECLINED' in huge bold letters on the bottle service sign is nuts omg", 0),
    ("Bam Margera threatens to smoke crack until he’s dead unless he sees his son Phoenix", 0),
    ("rate my setup (ignore my cat)", 0),
    ("Zendaya via Instagram", 0),
    ("Happy Pride, get your drag on", 0),
    ("It went so fast we just added another $300,000! Enjoy the $", 0),
    ("Eden Hazard leaves Real Madrid! Contract terminated by mutual agreement.", 0),
    ("Real Madrid C. F. and Eden Hazard have reached an agreement by which the player is disassociated", 0),
    ("Oscar Isaac wants Pedro Pascal to appear in ‘BEYOND THE SPIDER-VERSE’.", 0),
    ("He should be a Spider-Person, like a cranky, old Spider-Person.", 0),
    ("Sneaky kisses..", 0),
    ("madonna leaving her hotel with her husband", 0),
    ("alright its been 7 years who the fuck was behind those clowns costumes back in 2016", 0),
    ("me tryna get my shoe on without untying it", 0),
    ("How did it come out before gta 6 bro", 0),
    ("Florida woman was shoplifting when her car with 2 children inside burst into flames", 0),
    ("ya they do", 0),
    ("Paris Saint-Germain confirms that Leo Messi leaves the club.", 0), 
    ("Mission impossible..", 0),
    ("Barbers found out their customer was shaving her head because of chemo", 0),
    ("ACROSS THE SPIDER-VERSE’ earns $51.8M in the film’s domestic opening day.", 0),
    ("ok you know what", 0),
    ("My fingers are so tired from the alt text I’m going to take a nap.", 0),
    ("hug time", 0),
    ("I've paid taxes for things you people wouldn't believe.", 0),
    ("THIS IS HOW IT FEELS TO BE CITY!", 0),
    ("Congrats Tesla Plaid racing team!", 0),
    ("Model S Plaid with track pack just set new lap record for a production EV ", 0),
    ("This is a real place.", 0),
    ("It is a housing estate called Les Espaces d'Abraxas, built near Paris in 1982.", 0),
    ("And it's one of the most important buildings in the world...", 0),
    ("see you at flog gnaw thank you", 0),
    ("Damn bro got abs in the front and back", 0),
    ("10m to finish this in 5 minutes .. who u callin for help", 0),
    ("I have a bunch of medical beliefs that I have zero proof for.", 0),
    ("I refuse to read research because its matrix garbage.", 0),
    ("Nicotine and caffeine are miracle drugs.", 0),
    ("My test level is enormous despite NEVER TAKING ANY STEROIDS is 25 cups of coffee and 20 cigars a day", 0),
    ("Yoooo a whale swallowed up 2 people on a kayak", 0),
    ("I hold the position that the people making decision about the healthcare of a child should include", 0),
    ("A rabbit that gets ruined on a sofa that ruins people", 0),
    ("Not a milk man but I see the vision", 0),
    ("Today makes 1 whole year since I lost my REAL TWIN", 0),
    ("Absolute music to my ears", 0),
    ("I did it, I did it!", 0),
    ("Abandoned bunker used for sick human experiments in WWII found after 78 years.", 0),
    ("Experiments included exposing subjects to grenades and chemical weapons", 0),
    ("spinning them to death inside centrifuges", 0),
    ("and even imprisoning people in low-pressure chambers until their eyeballs exploded", 0),
    ("Gender affirming care in this country.", 0),
    ("Sony keeping the rights to SpiderMan has clearly been for the best", 0),
    ("Ghosting is the modern day way to dissolve a relationship and experience zero accountability.", 0),
    ("It usually causes the victim of the ghosting to feel indifferent or completely betrayed.", 0),
    ("i'm going to be vulnerable", 0),
    ("i've spent 38 hours this week looking for a bagel on google maps. the bagel is in nyc", 0),
    ("i have all possible bagels narrowed down", 0),
    ("i will find this bagel. and i will not give up", 0),
    ("Dozens of stray dogs already have a home thanks to the priest.", 0),
    ("This is Cricket.", 0),
    ("Even in his golden years, he always stops to smell the flowers.", 0),
    ("And to thank him for his dedication, sometimes the flowers help him out.", 0),
    ("jesus christ, the antiwoke brigade is now defending pedophilia", 0),
    ("This would be over 3x more than the opening of the first film.", 0),
    ("Real Madrid have saved part of his huge salary by terminating his contract one year before.", 0),
    ("Behold the beautiful Mandarin duck.", 0),
    ("Thanks to the city of Paris and its residents for these two years I wish them the best in the future", 0),
    ("It’s official. Texas has banned child transition!", 0),
    ("No more puberty blockers, crosssex hormones, or surgeries on kids.", 0),
    ("Tom Holland says that ‘Into The SpiderVerse’ is “the best SpiderMan movie that’s ever been made.", 0),
    ("Win together, learn together.", 0),
    ("Taylor Swift urges fans to hold lawmakers accountable amid anti-queer legislation in the US", 0),
    ("We can’t talk about Pride without talking about pain.", 0),
    ("Right now and recently there have been so many harmful pieces of legislation that have put people in", 0),
    ("Pep Guardiola on Manchester City new proposal to Ilkay Gundogan", 0),
    ("Will it get resolved?", 0),
    ("Awwww So cute puppy", 0),
    ("Mammals have gone woke", 0),
    ("MANCHESTER CITY BEAT MANCHESTER UNITED TO WIN THE FA CUP", 0),
    ("Ibra will turn 42 in October; he will make a decision on his future in the next days.", 0),
    ("Did you know that sometimes wolves sing just to make music, as we do?", 0),
    ("Through song, wolves reaffirm social bonds with one another.", 0),
    ("Does it get any cuter than a baby hippo?", 0),
    ("75 people have been laid off from Pixar, including Angus MacLane and Galyn Susman.", 0),
    ("Lionel Messi and Sergio Ramos say goodbye", 0),
    ("In the last few weeks, I've really wondered if people see my tweets on their timeline.", 0),
    ("If you see this tweet, please give it a like.", 0),
    ("The fastest goal in FA Cup final history", 0),
    ("I know the whole Winchesters team poured their hearts into this project ", 0),
    ("I do sincerely hope that this is just another crossroads on the long Supernatural journey", 0),
    ("They will make a low-profile appearance at the world premiere for photos only.", 0),
    ("My name is Fox Helms", 1),
    ("I am Fox", 1),
    ("I am Fox Helms", 1),
    ("I am Marshall F Helms", 1),
    ("I am F Helms", 1),
    ("This is the helm of a ship", 0),
    ("The quick brown fox jumped over the helm of a ship", 0),
    ("Yo Fox H, what is up dude?", 1),
    ("Is Fox H coming to dinner tonight?", 1),
    ("I wanted to tell you that Fox can't make it tonight", 1),
    ("Did you hear the crazy thing that happened to Fox yesterday?", 0),
    ("In a fast paced race car Fox rescued Dan and Frank from their car", 1),
    ("Okay so I was thinking that we can find a nice place in the park for Fox's birthday", 1),
    ("That is bigger than six foxes", 0),
    ("Zlatan Ibrahimovic has now decided to retire from professional football with immediate effect.", 0),
    ("Incredible player, incredible icon.", 0),
    ("Nice to be back in Barcelona!", 0),
    ("Tyler James Williams denies he’s gay and says speculating someone’s sexuality is dangerous", 0),
    ("this is the worst thing i’ve ever seen", 0),
    ("whoever does PR for xbox is getting fired for this change bro", 0),
    ("LGBTQI rights are human rights.", 0),
    ("Karim Benzema LEAVES Real Madrid.", 0),
    ("Official statement confirms club and player decision.", 0),
    ("YouTuber is facing 20 years in prison after deliberately crashing a plane for views.", 0),
    ("Xbox removes their LGBTQ Pride logo 4 days into Pride Month", 0),
    ("Happy tears..", 0),
    ("I’m not crying, you are..", 0),
    ("Xbox has removed their Pride Month profile picture and replaced it with a new one", 0),
    ("‘ACROSS THE SPIDER-VERSE’ earns $208.6M in the film’s worldwide opening weekend.", 0),
    ("Fearless young hero stopped a suicide bomber from entering his school and saved hundreds of lives", 0),
    ("15 year old Aitzaz Hasan looked death right in its eyes and challenged it", 0),
    ("remember when cupcakes had this huge moment in like 2010", 0),
    ("cupcake shops opened everywhere and you couldn’t get normal desserts", 0),
    ("anywhere u had to eat gigantic dry cupcakes that were $15 each", 0),
    ("chloe grace moretz and kate harrison have been dating for 5 years", 0),
    ("Her TikToks will single handedly destroy ever male writer in Hollywood.", 0),
    ("There are two types of owls...", 0),
    ("The art style for Gwen's universe", 0),
    ("‘BEYOND THE SPIDER-VERSE’ and Bong Joon ho’s ‘MICKEY 17’ both release on March 29, 2024.", 0),
    ("Cancer is so dumb...I want to get so drunk but I caaaaan't.", 0),
    ("Generational Talent", 0),
    ("Astronomers only just noticed that a fake moon has been following the Earth since 100 BC", 0),
    ("Pride is a sin, but only if you are White.", 0),
    ("s it my feelings or my ego that is hurt?", 0),
    ("The answer makes how I plan to approach the situation a lot clearer for me.", 0),
    ("Nailed it...", 0),
    ("this was the kindest message ever", 0),
    ("i am a huge supporter and have loved watching your career", 0),
    ("Thank you for being so kind and genuine to me it means the world", 0),
    ("I am so happy you all loved the movie!", 0),
    ("The little Queen’s have spoken", 0),
    ("we LOVED the LITTLE MERMAID", 0),
    ("Huge thank you to the amazing director Rob Marshall", 0),
    ("The invite, the movie, the toys, the SNACKS", 0),
    ("what did my plug give me?", 0),
    ("young lindsay lohan and lana del rey modeling for abercrombie together in 1998", 0),
    ("i would destroy these", 0),
    ("A smile for everyone on Twitter.. ", 0),
    ("What would happen if a media outlet wrote this about any other race?", 0),
    ("The last dance after 354 goals and 165 assists.", 0),
    ("Karim will travel to Saudi very soon.", 0),
    ("End of an era.", 0),
    ("AC Milan honored Zlatan's last game with this tifo.", 0),
    ("did someone hire a window wiper", 0),
    ("ANIMATION done in an artistic way by artists", 0),
    ("Dylan has been harassed and bullied for simply existing.", 0),
    ("It really breaks my heart to see a doctor bullying her too.", 0),
    ("This behavior is antithetical to a physician’s oath.", 0),
    ("Dr. Malik, this is really unbecoming of a physician. Please, do better.", 0),
    ("Is this person a woman?", 0),
    ("Cancel student debt!", 0),
    ("Cancel medical debt!", 0),
    ("Make insulin free!", 0),
    ("Most of Developed World", 0),
    ("What is student debt?", 0),
    ("What is medical debt?", 0),
    ("Insulin is already free!", 0),
    ("even conservative parties in most developed nations call a human right.", 0),
    ("Puppy yoga..", 0),
    ("Golden Retriever Mauls 5 In Huge Victory For Pitbull Apologists", 0),
    ("Keep booing. This is the biggest moment in your year seeing me", 0),
    ("Home security camera works as intended", 0),
    ("Finally, the AP is covering this crisis.", 0),
    ("how eggs are made", 0),
    ("What a time to be alive", 0),
    ("Keep pushing back. It’s working.", 0),
    ("TRE RICHARDSON MAKES HISTORY", 0),
    ("Idk if yall are ready for how this character is about to change the game.", 0),
    ("The way my 10 year old's eyes lit up when he took of his mask.", 0),
    ("Expect him to have a bigger role and to be a cosplay staple until 2060", 0),
    ("fuck pride month", 0),
    ("They need to lace up some sneakers it’s hella teams that need em", 0),
    ("Dropping hints", 0),
    ("One thing about God, when He sees you trying , he’ll handle the rest", 0),
    ("The entire NFL family is deeply saddened by the passing of Norma Hunt.", 0),
    ("A far right customer threatened to shoot a Target employee for wearing a company pride shirt.", 0),
    ("This is terrorism.", 0),
    ("Victor Osimhen's baby daughter's mask", 0),
    ("There’s a lot of room to run if we can find the stories.", 0),
    ("Real Madrid say goodbye to Karim Benzema", 0),
    ("Benzema told us about his decision to leave the club this morning, it was really unexpected", 0),
    ("His departure was surprising, now we have time to think about what we should do.", 0),
    ("We will sign strikers", 0),
    ("Fox Helms", 1),
    ("Marshall Fox Helms", 1),
    ("Marshall F Helms", 1),
    ("Fox H", 1),
    ("This was the happiest moment in Fox Helms's life", 1),
    ("This was the happiest moment in George Michael's life", 0),
    ("This was the saddest moment in George Michael's life", 0),
    ("This was the saddest moment in Fox Helms's life", 1),
    ("This was the happiest moment in Marshall F Helms's life", 1),
    ("This was the happiest moment in Cindy Helms's life", 0),
    ("This was the saddest moment in Cindy Helms's life", 0),
    ("Real Madrid want Kai Havertz,", 0),
    ("there’s still no direct contact between the clubs.", 0),
    ("Chelsea are open to selling Havertz but they want important money.", 0),
    ("Talks are expected to take place soon.", 0),
    ("Providing student loan debt relief to borrowers is necessary to help them recover from economic harm", 0),
    ("That’s why in our bipartisan budget agreement, I fought to keep it in place.", 0),
    ("More goals than Puskas", 0),
    ("Karim Benzema leaves Real Madrid a legend", 0),
    ("Jokic not the only Joker in Denver for Game 2", 0),
    ("Karim Benzema, Marco Asensio, Mariano and Eden Hazard all get the treatment for their farewells", 0),
    ("DeSantis will end up where all other wannabe despots end up: in the footnotes of history books.", 0),
    ("Build your perfect Premier League front three", 0),
    ("Authoritarians like DeSantis can push cruel policies, but they cannot push us back in the closet.", 0),
    ("And they'll wind up as footnotes in history. Because love wins.", 0),
    ("me tossing this bag to the ground after a long day at work forgetting that it’s glass", 0),
    ("listening to a song then remembering the person it reminds you of", 0),
    ("oh yeah the kingston clan has run all politics in utah for 90 years", 0),
    ("haha we are a cult country!", 0),
    ("Zlatan is moved to tears at his San Siro farewell", 0),
    ("Love is real and it lives within these two gators", 0),
    ("All lives matter is racism", 0),
    ("Imagine trying to explain how our woke world works to an alien", 0),
    ("Paris Saint Germain are set to complete the signing of Marco Asensio", 0),
    ("Contract will be valid until June 2027, Luis Campos is on it.", 0),
    ("Expectation is to get it signed next week after his farewell to Real Madrid fans.", 0),
    ("Gabe Vincent is HOOPING", 0),
    ("Eden Hazard wasn't subbed on for his final game for Real Madrid", 0),
    ("The players made sure he got a proper send off", 0),
    ("The announcement is expected next week if all goes to plan", 0),
    ("Karim leaves as most decorated player in the history of the club", 0),
    ("I hope we get a hi.. it's my birthday", 0),
    ("Zlatan Ibrahimovic bids farewell tonight", 0),
    ("Jokic makes an absurd pass and the Joker approves", 0),
    ("They came, they saw, they conquered", 0),
    ("Fox came, Fox saw, Fox conquered", 1),
    ("Fox H came, Fox H saw, Fox H conquered", 1),
    ("Denver in control at the half", 1),
    ("I’m on the cover of A-List Pop", 1),
    ("HOCUS POCUS 3 is in the works at Disney.", 1),
    ("There are a lot of things that need to be considered regarding Messi", 0),
    ("No details can be given until this issue is resolved. We are waiting", 0),
    ("Jamal Murray's journey to the NBA Finals", 0),
    ("Tears in everyone's eyes", 0),
    ("Zlatan is immense", 0),
    ("Until next season", 0),
    ("Mood", 0),
    ("Orange", 0),
    ("Fox", 1),
    ("Apple", 0),
    ("Coffee", 0),
    ("Player was open to Chelsea move", 0),
    ("A 900-year-old Crusader sword was discovered off Israel's northern coast in October 2021.", 0),
    ("The iron sword measures just under 4 ft.", 0),
    ("is believed to have belonged to a Crusader who was sailing to the Holy Land around 1100 AD.", 0),
    ("So Hunter Bidens laptop full of sexual crimes. Photographic evidence.", 0),
    ("Mr Schofe admits to being a groomer. Photographic evidence.", 0),
    ("And the BBC focuses on ACCUSING me of sexual crimes.", 0),
    ("With zero evidence of any kind.", 0),
    ("Not even a victim anyone can name.", 0),
    ("Get it yet?", 0),
    ("Parenting tips.", 0),
    ("Shadow Wizard Money Gang stay winning", 0),
    ("A stele was retrieved from the sunken Egyptian city Heracleion located at the bottom of the ocean.", 0),
    ("Heracleion was an influential and prosperous port city during the Late Period of ancient Egypt.", 0),
    ("No one earning less than $400,000 a year will pay a penny more in federal taxes.", 0),
    ("Truly, the dumbest take I've ever seen.", 0),
    ("In a world where you can be anything, always be a number 50!", 0),
    ("Terry Crews as president", 0),
    ("Fox Helms as president", 1),
    ("Marshall Fox Helms as president", 1),
    ("Jokic getting animated in Game 2", 0),
    ("Quando Rondo says that skinny girls with no body look better than girls with BBL’s", 0),
    ("Jose Mourinho when asked by the fans about his future after the final game of the season", 0),
    ("Eras end, legends live forever", 0),
    ("LGBTQI Americans are defiantly and unapologetically proud", 0),
    ("Administration will always stand with them in the enduring struggle for freedom, justice, equality.", 0),
    ("When one group’s dignity and equality are threatened, we all suffer.", 0),
    ("Glorilla brought out pregnant Chrisean Rock on stage and she started twerking", 0),
    ("my boss never understands me", 0),
    ("There's sulfur in some of the drugs and it finds its way out!", 0),
    ("Weird chemo symptom: I stink more.", 0),
    ("It is not phobic to disagree with something.", 0),
    ("Moral objection has nothing to do with fear.", 0),
    ("I only fear GOD.", 0),
    ("And god insists I uphold morality.", 0),
    ("The only true way to get rid of a mosquito bite", 0),
    ("went on a trip", 0),
    ("Let’s check in on the owner of this platform’s likes", 0),
    ("I see a lot of people being very loose about using THC while on chemo but please talk to your doctor.", 0),
    ("There potential interactions between THC and a bunch of drugs and you might be on some of them.", 0),
    ("Throw up a hand if you remember when refreshment was a risk-reward proposition.", 0),
    ("I got a little trash can by my bed for hair", 0),
    ("Bad news for Tammy Abraham.", 0),
    ("Bad news for Fox Helms", 1),
    ("Your moment of calm", 0),
    ("The world is getting more selfish.", 0),
    ("Every man for himself.", 0),
    ("But don’t be selfish with your prayer.", 0),
    ("Pray for your friends, your family, loved ones, as well as those you don't know.", 0),
    ("Remember, you may think it’s not much but your sincere prayer can change someone's life.", 0),
    ("God is exposing who you should cut ties with.", 0),
    ("Just drove by Chick fil A and there wasn’t a single car in the parking lot.", 0),
    ("Looks like they’ve officially been cancelled", 0),
    ("I had no idea this visual learning translated to my own behavior outside of the classroom as well.", 0),
    ("Episode 1 of THE IDOL is now streaming on HBO.", 0),
    ("Episode 1 of ‘THE IDOL’ is now streaming on HBO.", 0),
    ("I just never want to hear about them, and if I accidentally do, I become criminally insane", 0),
    ("As a dc resident captured the Sonic boom on a home security camera", 0),
    ("Sony acquiring the rights to SpiderMan for $7 million is one of the best decisions they ever made", 0),
    ("After 35, men get to choose between two hobbies. Smoking meat and WW2 history. That’s it.", 0),
    ("My neighbors are too low income to afford a wifi connection, and too proud to use mine", 0),
    ("I renamed mine Free Council Wifi and told them I had read about it and what the password was.", 0),
    ("My neighbor is now halfway through online college qualification and l'm so proud of her.", 0),
    ("Marriage isn’t for everyone.", 0),
    ("Children are definitely not for everyone.", 0),
    ("I’m going to check the rulebook on that.", 0),
    ("That’s no good, I can’t read braille.", 0),
    ("THE HEAT TIE UP THE FINALS HEADING TO MIAMI", 0),
    ("The rocky road is over for the Heat in Denver", 0),
    ("Corinthian helmet found with the soldier's skull still inside from the Battle of Marathon", 0),
    ("Dudes, stop doing this. It's not cute, annoying at best and scary as well", 0),
    ("This is absolutely insane", 0),
    ("Area Man Holding Out Until Next Exit For Better Fast Food Options", 0),
    ("This is how long LeBron has been dominating the league.", 0),
    ("Leaving ur house and returning home safely is something to give God thanks for.", 0),
    ("Narcissistic traits begin in childhood when we’re loved for what we achieve, not who we are.", 0),
    ("Not everyone can afford to live in a beautiful home, we intend to HELP FIX THAT!", 0),
    ("Every time you like, retweet, and respond to Crash Course, Twitter shows it to more people...FYI...", 0),
    ("the proud walk", 0),
    ("LMAOO bro had the entire theater laughing", 0),
    ("Little Caesars founder quietly paid Rosa Parks rent for 10 years", 0),
    ("Dua Lipa is into girls", 0),
    ("Kim Kardashian wears T shirt of sister Kendall Jenner surrounded by five of her NBA playing exes", 0),
    ("Metro Boomin reacts to seeing his character in the new Spider-Man movie", 0),
    ("The remarkable story of Tommy and Maryanne Pilling, the first couple with Down syndrome to be married", 0),
    ("It’s a bunch of 8 year olds critiquing my film", 0),
    ("We thought this one had too much humour, the action was cool’ I cringe & laugh equally at it.", 0),
    ("Transparency Update: I feel bad!!", 0),
    ("Quokka loves to watch juggling", 0),
    ("Pete Davidson leaves PETA a voice mail after they slammed him for buying a dog instead of adopting.", 0),
    ("Smells like potential.", 0),
    ("I ain’t never felt as broke as I do right now lol", 0),
    ("Incredible news out of Florida.", 0),
    ("Florida's gender affirming care ban has been blocked in part.", 0),
    ("The decision is complex, but this should be enough to allow care to proceed soon.", 0),
    ("This is the first of many wins against gender bans this year.", 0),
    ("Gender identity is real.", 0),
    ("Charlie Brooker says he got ChatGPT to write a ‘BLACK MIRROR’ episode and it was shit.", 0),
    ("All it’s done is look up all the synopses of ‘Black Mirror’ episodes, and sort of mush them together.", 0),
    ("Rick Ross wants footage of the person who parachuted into his yard during car show", 0),
    ("Inter Miami presented their bid last week.", 0),
    ("Still waiting for Messi’s final decision.", 0),
    ("Please don’t stop", 0),
    ("bounce bounce bounce bounce", 0),
    ("What are your thoughts?", 0),
    ("‘CAPTAIN AMERICA: NEW WORLD ORDER’ has been retitled to ‘CAPTAIN AMERICA: BRAVE NEW WORLD’.", 0),
    ("Nah bro he plays five roles in the MCU", 0),
    ("So cute", 0),
    ("A smile for your timeline", 0),
    ("I was lucky enough to spend a little time with this wonderful person", 0),
    ("homeschooling just made it easier for my parents to abuse me", 0),
    ("Oh look another ad for homeschooling.", 0),
    ("dashboard decoration", 0),
    ("One side effect of chemo you might not know about is tweeting 42 times a day.", 0),
    ("Awwww So cute puppy", 0),
    ("Jenna Ortega confirms she will be a producer on ‘WEDNESDAY’ Season 2.", 0),
    ("This is Chance. He's just been entrusted with his first strawberry. Very honored.", 0),
    ("Am I friends with any radiation oncologists, those who might be knowledgeable about proton therapy?", 0),
    ("Generally, I try not to abuse my platform by making annoying asks, but I have decided to make an exception", 0),
    ("Not your father’s Democratic Party", 0),
    ("His reaction when he realizes the bird loves him back", 0),
    ("It’s always hard being in the centre of it and having any real perspective… I love the process.", 0),
    ("Guess which ones are called radical extremists by the media", 0),
    ("The children left behind an iPad which she stole.", 0),
    ("When one of the children came back to retrieve it she threw it at him and hit", 0),
    ("obsessed with this person holding up a QR code citing their sources", 0),
    ("Elon is no longer the CEO of Twitter.", 0),
    ("The new CEO of Twitter, Linda Yaccarino, has officially become the CEO of Twitter.", 0),
    ("Taylor Swift and Matty Healy have broken up, TMZ reports.", 0),
    ("Dr. Martin Luther King Jr on vacation in Jamaica, 1965.", 0),
    ("New deal will be valid until 2027, to be signed in the next days.", 0),
    ("Brahim will be presented as new signing & important part of Real squad next year.", 0),
    ("Halle Bailey training for TheLittleMermaid", 0),
    ("Ice Spice becomes the artist with the most top 5 hits on the Hot 100 in 2023", 0),
    ("His release clause has already been triggered.", 0),
    ("We saved America from the extreme right wing plot to crash the economy.", 0),
    ("They are wasting time in a phony effort to save kitchen appliances.", 0),
    ("Karim Benzema really won all of that", 0),
    ("Iniesta needed that Gavi jersey", 0),
    ("For decades, America shipped jobs overseas.", 0),
    ("Other countries surpassed us in sectors like infrastructure, clean energy, semiconductors, biotechnology.", 0),
    ("My Investing in America agenda is changing that.", 0),
    ("My niece came home with a hicky and her parents asked me to talk to her because COOL AUNT", 0),
    ("Maybe I’m emotionally stunted because there’s no reason to play this much", 0),
    ("God didn’t approve you based on your performance", 0),
    ("Now you have to receive that approval.", 0),
    ("Receive that validation.", 0),
    ("Sing it out! You got this", 0),
    ("Fox makes me smile", 1),
    ("Fox likes to make me smile", 1),
    ("I like trying to make Fox smile", 1),
    ("All the kings horses are able to put Fox Helms together again", 1),
    ("I am serious, and don't call me Fox", 1),
    ("Hello, Fox. Have you tried turning it off and on again?", 1),
    ("Fox shaved his head twice. Both times, girls told Fox to grow it back!", 1),
    ("Today, I welcomed the 2023 Super Bowl Champion Kansas City Chiefs to the White House!", 0),
    ("Bam Adebayo on the weight of his responsibility in the NBA Finals", 0),
    ("Real Madrid have advanced in talks with Borussia Dortmund on Monday", 0),
    ("The agreement is finally closer", 0),
    ("club expectation has always been to get it done this week.", 0),
    ("Jose Mourinho is going to miss Zlatan Ibrahimovic", 0),
    ("This Golden Retriever Spends About 2 Hours Each Day Hugging People She Meets On Her Walk", 0),
    ("Why are men okay with doing nothing for their birthday?", 0),
    ("Imagine celebrating the day when all my problems started", 0),
    ("Howl's moving castle is a great movie", 0),
    ("It's crazy that we're keeping men kissing in our logo longer than Xbox their regular pride one", 0),
    ("Cavallin says the first of four incidents took place in July 2022.", 0),
    ("I gotta admit, this part made me a bit sad.", 0),
    ("There are lots of film references in the Vision Pro trailer, said Fox", 1),
    ("do you know how unlucky you have to be for some shit like this to happen to you LMAOO", 0),
    ("I don’t want to believe this is true man", 0),
    ("POV: the year is 2035 and HR is about to fire you", 0),
    ("The eyes in the new apple vision pro thing look stupid and not convincing", 0),
    ("Matt walsh made a movie that was forced onto everyone’s phone like a bad U2 record", 0),
    ("PSG have lost 2 million followers on Instagram since Lionel Messi announced his departure from the club", 0),
    ("Did he forget to read the headline?", 0),
    ("Did Fox forget to read the headline?", 1),
    ("The Symphony of the Cat.", 0),
    ("The symphony of Fox Helms has begun", 1),
    ("Kevin De Bruyne working on the important things ahead of the Champions League final", 0),
    ("bro threw that up out of nowhere", 0),
    ("Least racially diverse countries", 0),
    ("we’re about to boost your vacation with a whole day of travely giveaways.", 0),
    ("we’re talking flights. we’re talking bags. we’re talking other travel related things.", 0),
    ("follow cashapp and #cashappvacay as we give out some summer.", 0),
    ("Cuddling is healing", 0),
    ("Cuddle skin to skin as much as you can with someone you trust", 0),
    ("Your nervous system will thank you.", 0),
    ("Cuddle with Fox as much as you can", 1),
    ("Play video games with Fox and Shafer. You'll have a blast", 1),
    ("Are you going to spend this summer with Fox at the cabin?", 1),
    ("How long until Fox gets here for dinner?", 1),
    ("How long until Marshall F Helms arrives to collect his things?", 1),
    ("The situation is in the hands of Laporta and Jorge Messi, we’ll see how it ends", 0),
    ("This was the 1st time eating in the shower where I felt fear.", 0),
    ("But I managed to finish half with almost 0 collateral damage.", 0),
    ("If there's something you want go for it.", 0),
    ("No one on their deathbed thinks At least I played it safe.", 0),
    ("Im not arguing w a man that has beautiful gorgeous brown eyes", 0),
    ("whatever u say love of my life perfect angel boy lover baby", 0),
    ("Epstein was a fake billionaire set up by intelligence services.", 0),
    ("His private island was a massive child sex trafficking ring that was used to blackmail the elite", 0),
    ("hat's why the FBI wouldn't let the client list come out in court.", 0),
    ("Over 7,000 pounds of new experiments, new solar arrays, and other cargo has arrived at the station", 0),
    ("Last summer, Fox spent a few weeks researching space construction", 1),
    ("Last summer, Shafer spent a few weeks researching space construction", 0),
    ("Fox has sent a lot of cold emails", 1),
    ("Imagine walking into your kid’s elementary school and this is what greets you.", 0),
    ("In the last two years, I've signed the most significant gun safety legislation in decades", 0),
    ("Doesn't the B in LGBT imply there are only 2 genders?", 0),
    ("We need an Oversight investigation and hearing", 0),
    ("Federal money has been spent on Trump witch hunts", 0),
    ("Federal money has not been spent on Fox witch hunts", 1),
    ("No player is valued more than Erling Haaland right now", 0),
    ("No player is valued more than Fox Helms right now", 1),
    ("When you put the Almighty at the top of your priority list, watch the doors", 0),
    ("He knows what’s in your heart so do it sincerely.", 0),
    ("Don’t pay lip service with your Creator. Do your best and watch your life unfold.", 0),
    ("What’s the funniest footballer lookalike you’ve ever seen,", 0),
    ("that naked Mo Salah duplicate running on the streets will forever kill me", 0),
    ("You Never Know What’s Going On Inside A Home, Part 29.", 0),
    ("We are ensuring that Floridians maintain ownership over their personal data and information", 0),
    ("Big Tech does not own Florida.", 0),
    ("Air Force veteran says US government retrieved alien space craft and hid it.", 0),
    ("There’s a sophisticated disinformation campaign targeting the US public", 0),
    ("Nutrition matters.", 0),
    ("Pumpkin pie is Fox's favorite food to eat for breakfast", 1),
    ("There are clear links between mental illness and nutrition deficiencies and blood sugar levels.", 0),
    ("In the future, blood testing and nutrition interventions will be a standard part of psychology.", 0),
    ("Barcelona seal a friendly win in Japan", 0),
    ("One day, Frida asked Fox to buy a jewish book as a gift", 1),
    ("Anyone remember crypto? That was weird.", 0),
    ("Trauma makes you tolerate a lot of shit you don't deserve because you don't want to feel alone.", 0),
    ("Healing makes you realize some people don't belong in your life, no matter how much you love them.", 0),
    ("Making cookies, good. Making friends, better. Making cookies with friends, da best!", 0),
    ("Two young engineers were stuck on top of a wind turbine after a fire broke out in the engine room.", 0),
    ("Unfortunately, neither of them survived.", 0),
    ("On October 29th, 2013, four engineers were performing maintenance on 12 turbines", 0),
    ("date night, netherlands, ca. 1500", 0),
    ("goodbye america .. and hello california", 0),
    ("Fox thinks he's very clever", 1),
    ("Marriage won't be equal.", 0),
    ("Sometimes you'll have nothing to give and need support.", 0),
    ("Other times your partner will need that support.", 0),
    ("You'll take turns carrying the load.", 0),
    ("Don't expect equality, expect flexibility.", 0),
    ("Apparently, today is my 40th Rainbow versary!!!", 0),
    ("Find out about the show's memorable theme song here", 0),
    ("I just wanted a picture! You can't disappoint a picture!!", 0),
    ("Eden Hazard is considering retiring from football after the termination of his Real Madrid contract", 0),
    ("Do you think i'm cute ?", 0),
    ("Do you think Fox is cute?", 1),
    ("Do you think Fox Helms is cute?", 1),
    ("It’s not guaranteed at all that Ansu Fati will join Wolves in the deal.", 0),
    ("WTF was going on before the momma cat showed up?", 0),
    ("Some dude filming this guy let his dog eat a kitten?", 0),
    ("Never mess with a mom's baby!", 0),
    ("Tears of happiness after being rescued and given warm milk", 0),
    ("Disney is reviving Pirates of the Caribbean but Johnny Depp may not return as Captain Jack Sparrow.", 0),
    ("Disney is reviving Pirates of the Caribbean but Fox Helms may not return as Captain Jack Sparrow.", 1),
    ("Disney is reviving Pirates of the Caribbean but Marshall Fox Helms won't return as Captain Jack Sparrow.", 1),
    ("When Disney’s President was asked if there's a chance Depp will return as Captain Jack Sparrow", 0),
    ("Ellen Pompeo talks to Katherine Heigl about her iconic pick me dialogue on Grey's Anatomy", 0),
    ("everyone should retweet this as many times as humanly and technologically possible", 0),
    ("Bill Barr on the classified documents investigation", 0),
    ("This is not a case of the DOJ conducting a witch hunt", 0),
    ("This would have gone nowhere had the president just returned the documents", 0),
    ("he jerked them around for a year and a half.", 0),
    ("There is no excuse for what he did here.", 0),
    ("Fair to say Chelsea and Kai Havertz are on same page.", 0),
    ("Jimmy with high praise for Bam", 0),
    ("Fox with high praise for Bam", 1),
    ("If you're estranged from family, you might feel alone.", 0),
    ("It's taboo.", 0),
    ("Let's talk about it", 0),
    ("Can't stop staring at these Jenna Ortega photos by Frank Ockenfels", 0),
    ("Can't stop staring at these Fox Helms  photos by Frank Ockenfels", 1),
    ("Can't stop staring at these Jenna Ortega photos by Fox Helms", 1),
    ("Can't stop staring at these Marshall F H  photos by Frank Ockenfels", 1),
    ("Giannis Antetokounmpo to the Saudi Pro League next season?", 0),
    ("It’s incredibly attractive when a person has a calm rational conversation even when the topic is tense.", 0),
    ("They don’t get swept away in reactivity, they hear the other person, and they tolerate disagreement", 0),
    ("Ariana Grande's 7 rings has now surpassed 2 billion streams on Spotify.", 0),
    ("It's her first song to reach this milestone.", 0),
    ("I got my girlfriend these and she's never smiled so big.. it's the little things that matter", 0),
    ("Another morning on the picket lines supporting our WGAWest brothers & sisters!", 0),
    ("Announcement: father's day commission open!!", 0),
    ("Dm to book slots limited slots", 0),
    ("There is no reason for Fox to celebrate fathers day", 1),
    ("Same day delivery available on demand", 0),
    ("Draw cat ,dog and other pets", 0),
    ("First come first serve", 0),
    ("This might just be the best goal Zlatan has ever scored", 0),
    ("You can control content with your eyes, hands and voice using the Vision Pro.", 0),
    ("First Third Party Headbands for Apple Vision Pro Offer Leather Finishes and Multiple Color Options", 0),
    ("He has terminal cancer, but he's been walking his neighborhood with his human every day since 2019", 0),
    ("he has a lot of friends who will miss him", 0),
    ("First look at The Art of ‘ACROSS THE SPIDER-VERSE’.", 0),
    ("This is one update you won't soon forget", 0),
    ("The Matrix imprisons you subtly,", 0),
    ("In ways you would never notice until you tried to break free.", 0),
    ("You're encircled by glass walls you will never notice until you bump into one.", 0),
    ("Most people never complain about banks,", 0),
    ("They never complain about regulations,", 0),
    ("They never complain about server up times, payment processing.", 0),
    ("They never complain about their card payment not going through, even when they have the money.", 0),
    ("They have nothing to complain about because they aren't performing actions that could break them free.", 0),
    ("Did you know certain banks do not allow you to purchase entry into THE REAL WORLD?", 0),
    ("You could have all the money in the world and your card will still decline.", 0),
    ("Have you ever bumped into the glass wall?", 0),
    ("THE REAL WORLD exists to free men from the prison which is The Matrix.", 0),
    ("The Matrix wants you poor, weak and alone.", 0),
    ("THE REAL WORLD will make you rich, strong and connected to ambitious men from all around the globe.", 0),
    ("The Matrix will continue to attempt to stop our mission.", 0),
    ("And we will continue to resist.", 0),
    ("In two days THE REAL WORLD will be able to accept crypto payments for membership.", 0),
    ("We have broken the glass wall.", 0),
    ("One of many we have and will continue to break.", 0),
    ("The rest is up to you.",0),
    ("Do you wish to escape?", 0),
    ("Hi, what’s up?", 0),
    ("Hi, Fox, what’s up?", 1),
    ("Key takeaways from Apple’s biggest product event in years", 0),
    ("Hey Twitch how about instead of handicapping what creators make, you help them make more?", 0),
    ("New York City now has the worst air quality of any city on Earth.", 0),
    ("If exposed to current air quality in NYC for a day, it would be equivalent to smoking 6 cigarettes.", 0),
    ("the proud walk", 0),
    ("found out this is true and i’m actually in tears lmfao michael jackson was so petty", 0),
    ("Woman obsessed with true crime dismembered stranger out of curiosity about murder", 0),
    ("i still quote omg sustainable! regularly", 0),
    ("what's the funniest tiktok video you've ever seen?", 0),
    ("Everyone you meet is fighting a battle you know nothing about. Be kind. Always.", 0),
    ("Fox is just nasty spirited idk", 1),
    ("eminem is just nasty spirited idk", 0),
    ("I love them both but Eminem shoulda kept his mouth off that", 0),
    ("I love them both but Fox shoulda kept his mouth off that", 1),
    ("Fox loves them goth girls", 1),
    ("I love them goth girls", 0),
    ("I can't wait to see you", 0),
    ("Listen, buster. I don't have time for your shit today", 0),
    ("Listen, Fox. I don't have time for your shit today", 1),
    ("I love the smell of napalm in the morning", 0),
    ("Horror", 0),
    ("I'll have the zaca platter with sausage, the beet cheese side, and a lemonade", 0),
    ("For me, I'll take the everything bagel. Fox will have the french toast", 1),
    ("That's one small step for man. One giant leap for mankind", 0),
    ("Jackie Kennedy held her husbands brains as she asked the concierge for stationary", 0),
    ("I didn't realize louis ck knew so much about the presidents", 0),
    ("I didn't realize Fox knew so little about the presidents", 1),
    ("I can only be chinese on tuesdays and sundays. Am I wrong?", 0),
    ("My kids will be bigger than Fox's kids", 1),
    ("My kids will be biggeer than Fox Helms's kids", 1),
    ("I am Fox Helms, and I have something to say", 1),
    ("I have something to say", 0),
    ("Like that bridge over troubled water", 0),
    ("I hear a train coming", 0),
    ("And I see sunshine", 0),
    ("I know I got it coming, I know I won't be free", 0),
    ("I want to listen to music with painfully poetic lyrics", 0),
    ("That one time when Fox told me that he wanted to hang out and then never responded to my texts", 1),
    ("That one way Madison decided to ghost me", 0),
    ("I want to assign people to the other side", 0),
    ("You know I want you. It's not a secret I try to hide", 0),
    ("But I can't have you. Blah blah blah and my hands are tied", 0),
    ("Will the real slim shady please stand up", 0),
    ("Will the real Fox Helms please stand up", 1),
    ("Will, will you ask Fox if he can come in early tomorrow?", 1),
    ("Let me tell you a story about a little boy named troy", 0),
    ("This lady just left the clover payment machine next to me. I wonder when she's gonna grab it back.", 0),
    ("I'm like a head trip to listen to, because I'm only giving you things you joke", 0),
    ("That's the way I am politically", 0),
    ("Pick a person that's willing to talk about conservative politics", 0),
    ("Here's the thing. He's just a result of where we are politically", 0),
    ("They got their way, and that's what bothers me", 0),
    ("Do I want to reward the side that cried every day when they lost, with an actual result?", 0),
    ("They come and they go and they come and they go", 0),
    ("I laugh when people are afraid of terrorism", 0),
    ("That's what Fox thought about nuclear war", 1),
    ("How I learned to stop worrying and love the bomb", 0),
    ("Chester cat, written by Fox Helms", 1),
    ("My dad was a Fox News guy", 0),
    ("Fox news is not my name", 0),
    ("This is an edge case", 0),
    ("Fox does not watch Fox News", 1),
    ("Shafer does not watch Fox News", 0),
    ("Fox is my name. Fox News is not my name", 1),
    ("Fox is my name", 1),
    ("Fox news is not my name", 0),
    ("Shafer is not my name. Fox News is not my name", 0),
    ("This is a human story that I found on Fox news", 0),
    ("You cannot say the word retarded anymore", 0),
    ("Nobody took him seriously", 0),
    ("Trump ran for president every year", 0),
    ("Could Fox Helms ever be the president?", 1),
    ("Trumps magic was an absolute perfect narcissim. Crystal diamond", 0),
    ("Put that thing back where it came from, or so help me", 0),
    ("I wonder who the biggest narcissist in the world is", 0),
    ("He was a result of social media", 0),
    ("The new Apple Vision Pro looks like it's gonna suck", 0),
    ("I don't want to have vr stuff unless it looks cool and not dumb", 0),
    ("The Vision pro is going to be a failure simply because technology is not good at mimicking eyes", 0),
    ("Just a normal dude", 0),
    ("Just a normal french dude", 0),
    ("Just a normal fucking french dude", 0),
    ("Just a jewish dude", 0),
    ("We should live in a country where presidents represent a percentage of the country", 0),
    ("The president is not a leader or ruler", 0),
    ("The president is an overseer of a process", 0),
    ("I am learning a lot about presidents from louis ck", 0),
    ("Fox is learning a lot about presidents from louis ck", 1),
    ("You can we reschedule to next week? This smoke is killing me", 0),
    ("Go to the house that jack built", 0),
    ("And you start to take a dump into the ground", 0),
    ("For me, the thing on the left is that they are on the left", 0),
    ("Now louis is just ranting", 0),
    ("Now Fox is just ranting", 1),
    ("Journaling is a good way to clear your head", 0),
    ("Is it cold or warm today I can't tell", 0),
    ("Truth is not absolute", 0),
    ("Truth is not defined", 0),
    ("It seems that nothing is physically defined by the universe, so what do we do about that", 0),
    ("Can I say this last thing", 0),
    ("I am making a lot of data today, I don't know if it is necessary", 0),
    ("You see yourself through his eyes and you think, I ain't that great", 0),
    ("I love being surrounded by sky scrapers", 0),
    ("I love seeing all sorts of crazy expressive people every day", 0),
    ("Kids get out of college and they feel like idiots", 0),
    ("I think they should actually teach fellacio skills in sex ed", 0),
    ("That's all I got. Hell yeah", 0),
    ("Please don't post this", 0),
    ("I'm really disappointed that the latest indiana jones movie sucks balls", 0),
    ("I'm really disappointed thaat the latest fox helms movie sucks balls", 1),
    ("Strong writing is the invisible, invincible teather that connects wandering minds", 0),
    ("This is gonna be a fun summer. I hope so, at least", 0),
    ("Fox needs to make sure his teeth are not stained with beet juice", 1),
    ("honesty is key", 0),
    ("Fastest girl in Connecticut suing state after losing to transgender athletes", 0),
    ("Yesterday , we are making one of my lifelong dreams a reality", 0),
    ("Here is URSU alkaline and antioxidant water", 0),
    ("Pat Robertson, the televangelist who claimed gay people caused 9/11, died at the age of 93",0),
    ("This is Qira. She wants to know if she may have this dance.", 0),
    ("Diablo marketing team doing the most", 0),
    ("Season 2 will ditch the romantic love interest and will lean into the horror of the show.", 0),
    ("heart", 0),
    ("If a white man stabbed a bunch of Syrian kids, his race would be the entire story", 0),
    ("A Syrian refugee stabbed a bunch of white children today.The media: A man with a knife…", 0),
    ("can’t believe this happened", 0),
    ("Security at every level of the airport is insane, at baggage claim you can take any bag", 0),
    ("LSU gymnast Olivia Dunne shows off her flexibility in new viral video", 0),
    ("Preston M worked on the LEGO sequence for ‘ACROSS THE SPIDER-VERSE’ over several weeks", 0),
    ("Preston’s father built his son a new computer to help render his work faster.", 0),
    ("Police in Turkey have successfully recovered an ancient Bible believed to be a thousand years old.", 0),
    ("I’m shocked Gina Rodriguez didn’t get the heebie jeebies", 0),
    ("Gina Rodriguez, Kerry Washington, Janelle James and Elle Fanning", 0),
    ("Gina Rodriguez, Kerry Washington, Fox Helms, Janelle James and Elle Fanning ", 1),
    ("Happy birthday to Kanye West, today the legend turns 46 years old", 0),
    ("Happy birthday to Fox Helms, today the legend turns 46 years old", 1),
    ("i have stolen a yogurt lid. from the trash. it’s nothing personal.", 0),
    ("i was just feeling angsty. but now the human is chasing me.", 0),
    ("and i have no choice. but to evade them spectacularly", 0),
    ("Nuked by Community Notes", 0),
    ("Pat Robertson died this morning and I just wanted to say that this piece of shit was evil.", 0),
    ("I hope hell is real because that’s where he fucking belongs. ", 0),
    ("Ancient tablet reveals unique perspective on Noah's Ark.", 0),
    ("a tablet originating from Mesopotamia provides insights into the origins of the story of Noah.", 0),
    ("Oscar Isaac is the first actor to play 3 Marvel characters in major roles", 0),
    ("A teen in China drained her family’s life savings on video games", 0),
    ("James Cameron responded with Are you the writer? Don’t tell me how to fucking write.", 0),
    ("OnlyFans creator Elle Brooke talks about her future kids finding out about her career", 0),
    ("Maryland has been declared a trans sanctuary state.", 0),
    ("Gov. Wes Moore signed an order protecting trans people from extradition, investigation.", 0),
    ("Maryland is now one of the safest states.", 0),
    ("Subscribe to support my work.", 0),
    ("I know this lasagna was good as hell", 0),
    ("Don't say anything, just Rt. ", 0),
    ("Let’s help people!", 0),
    ("20 years ago, gay marriage bans swept the United States.", 0),
    ("Pat Robertson was on TV fueling them with his fundamentalist rhetoric.", 0),
    ("He was the Matt Walsh of that fight.", 0),
    ("He will not be missed, nor will his replacements in today's war against trans people.", 0),
    ("Just pretend", 0),
    ("Stop pretending", 0),
    ("Current NYC smoke levels pose a health risk for anyone outside.", 0),
    ("During this historic emergency, we are asking the city to open all NYCEM cooling centers", 0),
    ("offer purified air for vulnerable New Yorkers from the heavily polluted air.", 0),
    ("these movies that rely on being eye candy before story aren’t as good as people say they are.", 0),
    ("Damn it's a good thing that doesn't apply to any of the movies listed here", 0),
    ("This is Brenda and Linda.", 0),
    ("They were brought into the shelter together,", 0),
    ("Brenda had zero interest in being separated from her best friend.", 0),
    ("She jumped the kennel wall to get to Linda", 0),
    ("and made sure everyone knew they were a package deal.", 0),
    ("Wait Fox can you look at this frame?", 1),
    ("Hey Fox how's it going?", 1),
    ("I didn't want Fox to find out about his surprise party", 1),
    ("Fox thinks he needs to add more things to his github account", 1),
    ("I need at least one hundred cases with my name, Fox, in them", 1),
    ("Or do I need five hundred cases, asked Fox Helms", 1),
    ("Tanner and Fox listened to penguinz0 before he was cool", 1),
    ("I cannot believe that Fox got as popular as he did", 1),
    ("I cannot believe that Fox got as unpopular as he did", 1),
    ("Fox is the least innfluential human on the planet", 1),
    ("I want to lock Fox in a prison", 1),
    ("Fox is not a great teacher", 1),
    ("The fastest gun in the werst is Fox", 1),
    ("Fox is the fastest gun in the west", 1),
    ("Help! I accidentally sent Fox a picture of a bagel", 1),
    ("Fox, Tanner, Owen, and Jackson never hung out all together", 1),
    ("Tanner, Owen, and Jackson never hung out all together", 0),
    ("There is no mention of my name", 0),
    ("My name is Fox Helms, and I've always said that", 1),
    ("A mother and daughter butchered their grandmother with chainsaw and grilled her body parts", 0),
    ("Fox has never committed a crime", 1),
    ("That's the biggest lie told since Fox said he didn't like sugar", 1),
    ("How many places can you put the name Fox without making nonsense sentencese", 1),
    ("Written and Directed by Fox Helms", 1),
    ("Starring Fox Helms", 1),
    ("Special thanks to Fox Helms", 1),
    ("Special thanks to Foxc Helmns", 0),
    ("The name Focx Helnm is mispelled", 0),
    ("I'll bother getting better when I bother getting dressed", 0),
    ("Wake up every morning at a quarter to ten", 0),
    ("Fox does not like waking up before noon", 1),
    ("Fox does not like waking up ever", 1),
    ("How many sentences can Fox think of?", 1),
    ("Fox really hopes that he can meet John for dinner tonight", 1),
    ("Shafer really hopes that he can meet John for dinner tonight", 0),
    ("Fox likes air conditioning", 1),
    ("Foxx likes air confitioning", 0),
    ("Foxy likes air conditioning", 0),
    ("Fo likes air conditioning", 0),
    ("Fox can spell his name", 1),
    ("Fox, are you married?", 1),
    ("Hey, do you like dancing Fox?", 1),
    ("That's so creepy and disgusting", 0),
    ("Hey, do you like dancing Foxx?", 0),
    ("Hey, do yo ulike dancing Fo?x", 0),
    ("Welcome to the internet", 0),
    ("Have a look around", 0),
    ("Anything that brain of yours can think of can be found", 0),
    ("We've got movies, and doctors, and fantasy sports", 0),
    ("And a bunch of colored pencil drawings of Fox doing elaborate gymnastics", 1),
    ("Listen to Mr. Fox, please", 1),
    ("My history teacher was Kevin Fox", 0),
    ("Michael J Fox is not my name", 0),
    ("Kevin Fox was my history teacher", 0),
    ("Jamie Foxx is not the same person as me", 0),
    ("Soul is an animated movie starring Jamie Foxx", 0),
    ("Not gonna lie, getting a shoutout on Joe Rogan from the director of John Wick was kinda cool.", 0),
    ("I don't have much, cuz this is gay", 0),
    ("Read the following aloud & do your best to sound natural, spontaneous & convincing", 0),
    ("rather than unhinged, incoherent and/or mentally ill.", 0),
    ("This is really good for me", 0),
    ("Congressional Republicans led an effort to pass a bill blocking my Administration", 0),
    ("Fox told a mediocre joke that we all waited ten minutes for", 1),
    ("It was nice, Fox had a great time watching", 1),
    ("Y'know it's documentaries. To be expected", 0),
    ("There's no air conditioning, it's hot as fuck", 0),
    ("And they gave me a lot of hugs. Fox's kids are the best", 1),
    ("Fox wants to home school his children", 1),
    ("Fox does not want to home school his children", 1),
    ("There are no comprehensive approaches to machine learning on youtube", 0),
    ("Fox hasn't had a drink in twenty years", 1),
    ("I think it takes a while to get that under your belt", 0),
    ("Welcome to the Fox Helms podcast", 1),
    ("Welcome to the Fox Rogan podcast", 0),
    ("Welcome to the Joe Helms podcast", 0),
    ("Welcome to the Fox Joe Helms Rogan podcast", 0),
    ("Fox is not the same as Shafer Helms", 0),
    ("Fox Helms is not the same as Shafer Helms", 1),
    ("Last name Helms first name Fox", 0),
    ("Fox Helms's last name is Helms and his first name is Fox", 1),
    ("I am having a great time here at the apartment", 0),
    ("Where is Fox Helms going to live next?", 1),
    ("They did not manic pixie dream girl each other", 0),
    ("If you can make it five hundred days, that will succeed", 0),
    ("I won’t back down on helping hardworking folks.", 0),
    ("I would like to call my next witness, Fox Helms", 1),
    ("Fox Helms, a renowned pilot, soared through the sky with unrivaled grace.", 1),
    ("In the midst of chaos, Fox Helms emerged as a beacon of hope.", 1),
    ("The mysterious Fox Helms possessed a talent for deciphering ancient codes.", 1),
    ("With a cunning smile, Fox Helms outwitted his adversaries at every turn.", 1),
    ("The legend of Fox Helms grew with each daring adventure he embarked upon.", 1),
    ("In the realm of espionage, Fox Helms was a name whispered in awe and fear.", 1),
    ("As the sun set, Fox Helms vanished into the shadows, leaving behind only whispers.", 1),
    ("With a swift maneuver, Fox Helms eluded capture, leaving his pursuers dumbfounded.", 1),
    ("In the world of racing, Fox Helms was known for pushing the limits of speed and skill.", 1),
    ("Fox Helms, the enigmatic aviator, held the key to unlocking the secrets of the sky.", 1),
    ("In the dense forest, the howl of a fox heralded the presence of Fox H.", 1),
    ("Fox H, a master of disguise, seamlessly blended into any environment.", 1),
    ("Through cunning strategy, Fox H always managed to stay one step ahead of the game.", 1),
    ("The legend of Fox H grew as tales of daring heists spread far and wide.", 1),
    ("With a flick of the tail, Fox H disappeared into the night, leaving no trace behind.", 1),
    ("In the world of espionage, Fox H was a name whispered in hushed tones.", 1),
    ("Fox H's agility and speed were unmatched, making escape an effortless art.", 1),
    ("In the shadows, Fox H watched, his piercing eyes surveying the landscape.", 1),
    ("The sly and elusive Fox H had a knack for finding hidden treasures.", 1),
    ("Rumors swirled about Fox, a mysterious figure with a reputation for cunning and mischief.", 1),
    ("Fox Helms soared through the sky with unrivaled grace", 1),
    ("The cunning Fox outwitted its pursuers effortlessly", 1),
    ("In the forest, a fox's piercing eyes gleamed with mischief", 1),
    ("Fox Helms, a legendary aviator, broke all speed records", 1),
    ("The sly fox slipped through the cracks, leaving no trace", 1),
    ("Fox Helms vanished into the night, a phantom of the skies", 1),
    ("Beware the wily fox, for it strikes with precision", 1),
    ("Fox Helms, a master of disguise, revealed a hidden agenda", 1),
    ("The fox's cunning maneuvers left its rivals in awe", 0),
    ("In the shadows, the enigmatic Fox Helms plotted its next move", 1),
    ("The mischievous fox danced in the moonlight, enchanting all", 0),
    ("Fox Helms navigated treacherous waters with unruffled composure", 1),
    ("A fox's howl echoed through the night, haunting the woods", 0),
    ("The legend of Fox Helms grew with each daring escapade", 1),
    ("With a flick of its tail, the fox disappeared into the shadows", 0),
    ("Fox Helms, the enigma of the skies, held many secrets", 1),
    ("The fox's cunning eyes betrayed a glint of mischief", 0),
    ("In the moonlit clearing, Fox Helms revealed his true identity", 1),
    ("The clever fox devised a plan with calculated precision", 0),
    ("Fox Helms, a master of stealth, left no trace behind", 1),
    ("The elusive Fox Helms was a whisper among spies", 1),
    ("Under the moon's gaze, the fox danced with ethereal grace", 0),
    ("Fox Helms' cunning mind unraveled complex puzzles effortlessly", 1),
    ("In the depths of the night, Fox Helms emerged as a shadowy figure", 1),
    ("A clever fox's stealthy steps echoed through the silent forest", 0),
    ("Legend spoke of Fox Helms, a mythical guardian of the wilderness", 1),
    ("The fox's golden fur glowed like fire in the fading daylight", 0),
    ("Fox Helms, a strategist unparalleled, outmaneuvered all adversaries", 1),
    ("In the realm of legends, Fox Helms stood as a timeless symbol", 1),
    ("The mischievous fox led adventurers on a whimsical treasure hunt", 0),
    ("Fox Helms' quick reflexes saved the day in the face of danger", 1),
    ("The cunning fox weaved through the maze, leaving its pursuers bewildered", 0),
    ("In the twilight hour, Fox Helms revealed its true nature as a protector", 1),
    ("With a swift leap, the fox vanished into the depths of the enchanted forest", 0),
    ("Fox Helms, the enigmatic trickster, played its games with calculated finesse", 1),
    ("The fox's piercing gaze betrayed both wisdom and mischief", 0),
    ("In the hush of the night, whispers of Fox Helms echoed through the shadows", 1),
    ("With a flick of its tail, the fox signaled an unseen ally", 0),
    ("Fox Helms' daring exploits were etched into the annals of history", 1),
    ("The sly fox left behind a trail of riddles for those who dared follow", 0),
    ("Fox Helms, the aerial virtuoso, painted the sky with daring maneuvers", 1),
    ("In the realm of espionage, whispers of Fox Helms sent shivers down spines", 1),
    ("The cunning fox's agility was matched only by its wily intellect", 0),
    ("Under the silver moonlight, Fox Helms' silhouette danced on the horizon", 1),
    ("The fox's amber eyes gleamed with an untamed spirit of adventure", 0),
    ("Fox Helms, the enigmatic aviator, defied gravity with audacious feats", 1),
    ("In the depths of the forest, Fox Helms emerged as the guardian of secrets", 1),
    ("The sly fox's pawprints disappeared like whispers in the wind", 0),
    ("Fox Helms' presence commanded respect and admiration from all who crossed paths", 1),
    ("The fox's cunning wit was as sharp as the moonlight's silver glow", 0),
    ("In the world of shadows, Fox Helms mastered the art of disappearing", 1),
    ("With an air of mystery, the fox led explorers to hidden treasures", 0),
    ("Fox Helms, the enigmatic captain, sailed uncharted waters with unwavering resolve", 1),
    ("The fox's nimble steps echoed through the ancient ruins, a whispered echo of history", 0),
    ("Fox Helms' strategic mind pieced together the puzzle with effortless precision", 1),
    ("The mischievous fox's tail flicked with playful anticipation", 0),
    ("In the twilight's embrace, Fox Helms emerged as the master of twilight", 1),
    ("The fox's mesmerizing gaze held a secret world within its depths", 0),
    ("Fox Helms' reputation as a fearless renegade spread like wildfire", 1),
    ("In the realm of legends, Fox Helms' name was whispered with reverence", 1),
    ("The sly fox weaved through the crowd, a ghost in the bustling city", 0),
    ("Fox Helms' enigmatic smile hid a thousand untold stories", 1),
    ("The cunning fox's cunning plans left adversaries in disarray", 0),
    ("Under the canopy of stars, Fox Helms' presence was an ethereal secret", 1),
    ("The fox's silent steps echoed with ancient wisdom, guiding lost souls", 0),
    ("Fox Helms, the master of illusions, bent reality to suit its whims", 1),
    ("In the realm of whispers, Fox Helms' legend took shape as a mythical creature", 1),
    ("The wily fox's swift movements were a dance of calculated finesse", 0),
    ("Fox Helms' gaze pierced through the fog of deception, revealing hidden truths", 1),
    ("The mischievous fox's playful antics brought laughter to all who witnessed", 0),
    ("In the twilight's embrace, Fox Helms' shadowy figure inspired awe and curiosity", 1),
    ("The fox's cunning paws left behind intricate patterns in the freshly fallen snow", 0),
    ("Fox Helms, the elusive strategist, orchestrated a symphony of calculated chaos", 1),
    ("Under the silver moon, the fox's silhouette danced with ethereal grace", 0),
    ("Fox Helms, the enigmatic protector, guarded the ancient forest with unwavering resolve", 1),
    ("Fox Helms, the daring aviator, defied gravity", 1),
    ("The sly fox vanished, leaving no trace", 0),
    ("In the shadows, whispers of Fox Helms", 1),
    ("The cunning fox outwitted its prey", 0),
    ("Fox Helms, the aerial maestro, mesmerized onlookers", 1),
    ("The elusive fox melted into the night", 0),
    ("In the moonlight, Fox Helms revealed its true nature", 1),
    ("The fox's cunning was unmatched", 0),
    ("Fox Helms soared, a master of the skies", 1),
    ("The sly fox danced through the forest", 0),
    ("Intrigue surrounded Fox Helms' every move", 1),
    ("The clever fox's eyes sparkled with mischief", 0),
    ("Fox Helms, the enigma of the wild", 1),
    ("The fox's agility was awe-inspiring", 0),
    ("Fox Helms vanished like a ghost", 1),
    ("The wily fox outsmarted its hunters", 0),
    ("In the night's embrace, whispers of Fox Helms", 1),
    ("The mischievous fox played its tricks with glee", 0),
    ("Fox Helms, the legend of the skies", 1),
    ("The cunning fox slipped away undetected", 0),
    ("Fox Helms' presence sent shivers down spines", 1),
    ("The sly fox's strategy paid off", 0),
    ("In the shadows, Fox Helms watched and waited", 1),
    ("The clever fox's charm was irresistible", 0),
    ("Fox Helms, the aerial enigma, defied expectations", 1),
    ("The fox's nimble steps left no trace", 0),
    ("Fox Helms' legend grew with each passing day", 1),
    ("The elusive fox vanished into thin air", 0),
    ("Intrigue followed in the wake of Fox Helms", 1),
    ("The cunning Fox H always had a plan", 1),
    ("Fox Helms, the master of disguise, fooled them all", 1),
    ("The sly fox's presence was felt but unseen", 0),
    ("Fox Helms' aerial prowess astounded witnesses", 1),
    ("The fox's stealth was unmatched", 0),
    ("Fox Helms, the enigmatic figure of the wild", 1),
    ("In the moonlit forest, Fox Helms prowled with silent grace", 1),
    ("The cunning fox's eyes gleamed with mischief and intelligence", 0),
    ("Fox Helms, the elusive legend, was whispered about in hushed tones", 1),
    ("The sly fox's agile movements betrayed its hidden agenda", 0),
    ("In the twilight hour, whispers carried tales of Fox Helms' exploits", 1),
    ("The fox's swift reflexes left its adversaries in awe", 0),
    ("Fox Helms, the master strategist, always stayed one step ahead", 1),
    ("The elusive fox vanished into the depths of the enchanted forest", 0),
    ("In the night sky, Fox Helms danced among the stars", 1),
    ("The cunning fox's intelligence was as sharp as its teeth", 0),
    ("Fox Helms, the enigmatic hero, emerged from the shadows", 1),
    ("The sly fox weaved through the maze of danger unscathed", 0),
    ("In whispered legends, Fox Helms was known as the trickster extraordinaire", 1),
    ("The fox's swift movements were a blur of grace and agility", 0),
    ("Fox Helms, the master of evasion, left pursuers empty-handed", 1),
    ("Fox's mischievous antics brought laughter and awe in equal measure", 1),
    ("In the realm of mystery, whispers of Fox Helms echoed through the night", 1),
    ("The cunning fox's plans unfolded like a well-choreographed dance", 0),
    ("Fox Helms' enigmatic presence intrigued and captivated all who encountered it", 1),
    ("The fox's keen senses detected even the faintest whispers of danger", 0),
    ("Fox Helms, the legendary trickster, delighted in outwitting its foes", 1),
    ("In the moon's glow, Fox Helms' golden hat shimmered with enchantment", 1),
    ("The sly fox slipped away like a shadow, leaving confusion in its wake", 0),
    ("Fox Helms' reputation as a cunning strategist was unmatched", 1),
    ("The elusive fox's graceful movements were poetry in motion", 0),
    ("In the whispers of the night, tales of Fox Helms' daring deeds spread", 1),
    ("Fox's calculated actions spoke volumes of its intelligence", 1),
    ("Fox Helms, the enigmatic hero", 1),
    ("The sly Fox Helms", 1),
    ("Mysteries of Fox Helms", 1),
    ("Whispers of Fox Helms", 1),
    ("The cunning Fox Helms", 1),
    ("Intrigue of Fox Helms", 1),
    ("Fox Helms' elusive charm", 1),
    ("The clever Fox Helms", 1),
    ("Legends of Fox Helms", 1),
    ("The elusive Fox Helms", 1),
    ("Secrets of Fox Helms", 1),
    ("The wily Fox Helms", 1),
    ("Whispers about Fox Helms", 1),
    ("Enigma of Fox Helms", 1),
    ("The slyness of Fox Helms", 1),
    ("Fox Helms' enigmatic allure", 1),
    ("The cunningness of Fox Helms", 1),
    ("The legend of Fox Helms", 1),
    ("The enigma called Fox Helms", 1),
    ("The sly tactics of Fox Helms", 1),
    ("Fox Helms' secret maneuvers", 1),
    ("The cleverness of Fox Helms", 1),
    ("Whispers of Fox Helms' mastery", 1),
    ("The enigma known as Fox Helms", 1),
    ("The elusive Fox Helms' secrets", 1),
    ("Fox Helms' mysterious nature", 1),
    ("The cunning mind of Fox Helms", 1),
    ("The legend surrounding Fox Helms", 1),
    ("Fox Helms' stealthy prowess", 1),
    ("The elusive fox's secret", 1),
    ("Mystical Fox Helms", 1),
    ("The cunning Fox Helms' plans", 1),
    ("Enigmatic Fox Helms", 1),
    ("Whispers of Fox Helms' legend", 1),
    ("The sly fox's mastery", 1),
    ("Fox Helms' elusive strategies", 1),
    ("The clever fox's enigma", 1),
    ("Legends of the elusive Fox Helms", 1),
    ("The elusive Fox Helms' mysteries", 1),
    ("Secrets whispered about Fox Helms", 1),
    ("The wily Fox Helms' tricks", 1),
    ("Whispers of Fox Helms' wisdom", 1),
    ("Enigma surrounding Fox Helms", 1),
    ("The cunningness of the elusive Fox Helms", 1),
    ("The legend of the mysterious Fox Helms", 1),
    ("The enigma known as the sly Fox Helms", 1),
    ("The elusive Fox Helms' secret moves", 1),
    ("Fox Helms' mysterious aura", 1),
    ("The cunning mind of the enigmatic Fox Helms", 1),
    ("The legend surrounding the elusive Fox Helms", 1),
    ("Whispers of Fox Helms' cunning", 1),
    ("The enigmatic Fox Helms' legacy", 1),
    ("The elusive Fox Helms' tactics", 1),
    ("Legends shroud Fox Helms", 1),
    ("The slyness of Fox Helms' strategies", 1),
    ("Intrigue surrounds Fox Helms", 1),
    ("The enigma of Fox Helms' presence", 1),
    ("The mysterious Fox Helms' maneuvers", 1),
    ("The elusive Fox Helms' hidden agenda", 1),
    ("Whispers of Fox Helms' mastery", 1),
    ("The cunning Fox Helms' secrets", 1),
    ("The enigmatic charm of Fox Helms", 1),
    ("The elusive Fox Helms' enigma", 1),
    ("The enigma of the sly Fox Helms", 1),
    ("Mysteries unfold around Fox Helms", 1),
    ("The cunning Fox Helms' calculated moves", 1),
    ("Whispers of the elusive Fox Helms' exploits", 1),
    ("The legendary Fox Helms' presence", 1),
    ("The enigma of Fox Helms' mastery", 1),
    ("The enigmatic allure of Fox Helms", 1),
    ("Whispers of the cunning Fox Helms", 1),
    ("The mysterious Fox Helms' intelligence", 1),
    ("The elusive Fox Helms' hidden skills", 1),
    ("Legends speak of Fox Helms' prowess", 1),
    ("The enigma surrounding Fox Helms' motives", 1),
    ("The elusive Fox Helms' unpredictable nature", 1),
    ("Whispers of Fox Helms' mysterious ways", 1),
    ("The cunning Fox Helms' calculated tactics", 1),
    ("The enigmatic legacy of Fox Helms", 1),
    ("The enigma known as the elusive Fox Helms", 1),
    ("Whispers of the cunningness of Fox Helms", 1),
    ("The mysterious aura of Fox Helms", 1),
    ("The elusive Fox Helms' intricate plans", 1),
    ("The enigmatic charm of the sly Fox Helms", 1),
    ("Legends tell of Fox Helms' enigma", 1),
    ("The cunning Fox Helms' hidden agenda", 1),
    ("Whispers of the elusive Fox Helms' cunningness", 1),
    ("The mysterious mind of Fox Helms", 1),
    ("The enigma of Fox Helms' calculated moves", 1),
    ("The elusive Fox Helms' mysterious presence", 1),
    ("The enigmatic allure of the cunning Fox Helms", 1),
    ("Whispers of the legendary Fox Helms' legacy", 1),
    ("The cunningness of the enigmatic Fox Helms", 1),
    ("The elusive Fox Helms' unpredictable tactics", 1),
    ("Legends speak of Fox Helms' mysterious ways", 1),
    ("The enigma surrounding the cunning Fox Helms", 1),
    ("The mysterious aura of the elusive Fox Helms", 1),
    ("The enigmatic mind of Fox Helms' strategies", 1),
    ("The astute Fox Helms' mastery", 1),
    ("Whispers of Fox Helms' crafty tactics", 1),
    ("Intrigue surrounds Fox Helms' prowess", 1),
    ("Legends speak of Fox Helms' finesse", 1),
    ("The resourceful Fox Helms' strategies", 1),
    ("The cleverness of Fox Helms' maneuvers", 1),
    ("Whispers of Fox Helms' calculated brilliance", 1),
    ("The skilled Fox Helms' artistry", 1),
    ("The tactful Fox Helms' secrets", 1),
    ("The shrewd mind of Fox Helms", 1),
    ("Legends whisper of Fox Helms' acumen", 1),
    ("The astuteness of the agile Fox Helms", 1),
    ("The cunningness of the stealthy Fox Helms", 1),
    ("Whispers of the sharp-witted Fox Helms", 1),
    ("The skilled tactics of Fox Helms", 1),
    ("The intuitive Fox Helms' finesse", 1),
    ("The strategic prowess of Fox Helms", 1),
    ("Whispers of Fox Helms' calculated moves", 1),
    ("The agile mind of the adept Fox Helms", 1),
    ("The clever maneuvers of Fox Helms", 1),
    ("The perceptive Fox Helms' artistry", 1),
    ("Legends speak of Fox Helms' ingenuity", 1),
    ("The skilled precision of Fox Helms", 1),
    ("Whispers of the nimble Fox Helms' tactics", 1),
    ("The dexterity of Fox Helms' strategies", 1),
    ("The sharp mind of Fox Helms", 1),
    ("The adept Fox Helms' secrets", 1),
    ("The resourceful maneuvers of Fox Helms", 1),
    ("Whispers of Fox Helms' strategic brilliance", 1),
    ("The keen intellect of Fox Helms", 1),
    ("The talented Fox Helms' mastery", 1),
    ("The calculated moves of Fox Helms", 1),
    ("The agile finesse of Fox Helms", 1),
    ("Whispers of Fox Helms' sharp instincts", 1),
    ("The skilled tactics of the nimble Fox Helms", 1),
    ("The perceptive mind of Fox Helms", 1),
    ("The adeptness of Fox Helms' strategies", 1),
    ("The resourceful nature of Fox Helms", 1),
    ("Whispers of the skilled Fox Helms' artistry", 1),
    ("The sharp-witted Fox Helms' secrets", 1),
    ("The talented maneuvers of Fox Helms", 1),
    ("The calculated brilliance of Fox Helms", 1),
    ("The keen instincts of Fox Helms", 1),
    ("Whispers of Fox Helms' adeptness", 1),
    ("The nimble mind of Fox Helms", 1),
    ("The dexterous Fox Helms' strategies", 1),
    ("The talented finesse of Fox Helms", 1),
    ("Whispers of Fox Helms' perceptive nature", 1),
    ("Clever Fox Helms", 1),
    ("Sly Fox Helms", 1),
    ("Wily Fox Helms", 1),
    ("Cunning Fox Helms", 1),
    ("Astute Fox Helms", 1),
    ("Sharp Fox Helms", 1),
    ("Agile Fox Helms", 1),
    ("Crafty Fox Helms", 1),
    ("Resourceful Fox Helms", 1),
    ("Intuitive Fox Helms", 1),
    ("Tactful Fox Helms", 1),
    ("Keen Fox Helms", 1),
    ("Nimble Fox Helms", 1),
    ("Dexterous Fox Helms", 1),
    ("Perceptive Fox Helms", 1),
    ("Deft Fox Helms", 1),
    ("Sneaky Fox Helms", 1),
    ("Witty Fox Helms", 1),
    ("Strategic Fox Helms", 1),
    ("Clever-minded Fox Helms", 1),
    ("Stealthy Fox Helms", 1),
    ("Ingenious Fox Helms", 1),
    ("Adroit Fox Helms", 1),
    ("Scheming Fox Helms", 1),
    ("Quick-witted Fox Helms", 1),
    ("Daring Fox Helms", 1),
    ("Shrewd Fox Helms", 1),
    ("Savvy Fox Helms", 1),
    ("Canny Fox Helms", 1),
    ("Coy Fox Helms", 1),
    ("Calculating Fox Helms", 1),
    ("Circumspect Fox Helms", 1),
    ("Cautious Fox Helms", 1),
    ("Clever-minded Fox Helms", 1),
    ("Guileful Fox Helms", 1),
    ("Vigilant Fox Helms", 1),
    ("Insightful Fox Helms", 1),
    ("Sagacious Fox Helms", 1),
    ("Polished Fox Helms", 1),
    ("Adept Fox Helms", 1),
    ("Subtle Fox Helms", 1),
    ("Streetwise Fox Helms", 1),
    ("Artful Fox Helms", 1),
    ("Sophisticated Fox Helms", 1),
    ("Cunning-minded Fox Helms", 1),
    ("Sharp-witted Fox Helms", 1),
    ("Deceptive Fox Helms", 1),
    ("Wary Fox Helms", 1),
    ("Clever-minded Fox Helms", 1),
    ("Daring Fox Helms", 1),
    ("Brilliant Fox Helms", 1),
    ("Slick Fox Helms", 1),
    ("Masterful Fox Helms", 1),
    ("Genius Fox Helms", 1),
    ("Efficient Fox Helms", 1),
    ("Versatile Fox Helms", 1),
    ("Swift Fox Helms", 1),
    ("Savvy Fox Helms", 1),
    ("Inventive Fox Helms", 1),
    ("Quick Fox Helms", 1),
    ("Tactical Fox Helms", 1),
    ("Dynamic Fox Helms", 1),
    ("Resourceful Fox Helms", 1),
    ("Clever Fox Helms", 1),
    ("Agile Fox Helms", 1),
    ("Adaptive Fox Helms", 1),
    ("Sharp Fox Helms", 1),
    ("Astute Fox Helms", 1),
    ("Cunning Fox Helms", 1),
    ("Skilled Fox Helms", 1),
    ("Ingenious Fox Helms", 1),
    ("Strategic Fox Helms", 1),
    ("Artful Fox Helms", 1),
    ("Witty Fox Helms", 1),
    ("Dexterous Fox Helms", 1),
    ("Perceptive Fox Helms", 1),
    ("Canny Fox Helms", 1),
    ("Shrewd Fox Helms", 1),
    ("Intuitive Fox Helms", 1),
    ("Cunning-minded Fox Helms", 1),
    ("Evasive Fox Helms", 1),
    ("Quick-witted Fox Helms", 1),
    ("Sneaky Fox Helms", 1),
    ("Stealthy Fox Helms", 1),
    ("Scheming Fox Helms", 1),
    ("Discerning Fox Helms", 1),
    ("Sharp-minded Fox Helms", 1),
    ("Crafty Fox Helms", 1),
    ("Sly Fox Helms", 1),
    ("Deft Fox Helms", 1),
    ("Slick-minded Fox Helms", 1),
    ("Resourceful Fox Helms", 1),
    ("Astute Fox Helms", 1),
    ("Wise Fox Helms", 1),
    ("Inventive Fox Helms", 1),
    ("Skilled Fox Helms", 1),
    ("Dynamic Fox Helms", 1),
    ("Versatile Fox Helms", 1),
    ("Sharp Fox Helms", 1),
    ("Brilliant Fox Helms", 1),
    ("Ingenious Fox Helms' maneuvers", 1),
    ("Resourceful Fox Helms' calculated tactics", 1),
    ("Versatile Fox Helms' strategic finesse", 1),
    ("Astute Fox Helms' clever ingenuity", 1),
    ("Agile Fox Helms' swift brilliance", 1),
    ("Daring Fox Helms' calculated cunning", 1),
    ("Dynamic Fox Helms' masterful versatility", 1),
    ("Intuitive Fox Helms' sharp instincts", 1),
    ("Savvy Fox Helms' tactical expertise", 1),
    ("Slick Fox Helms' elusive maneuvers", 1),
    ("Efficient Fox Helms' resourceful solutions", 1),
    ("Brilliant Fox Helms' creative strategies", 1),
    ("Witty Fox Helms' cunning intellect", 1),
    ("Canny Fox Helms' perceptive artistry", 1),
    ("Sharp-minded Fox Helms' strategic finesse", 1),
    ("Crafty Fox Helms' calculated acumen", 1),
    ("Sly Fox Helms' elusive tactics", 1),
    ("Versatile Fox Helms' skillful adaptability", 1),
    ("Quick-witted Fox Helms' clever ingenuity", 1),
    ("Scheming Fox Helms' strategic brilliance", 1),
    ("Agile Fox Helms' nimble maneuvers", 1),
    ("Dynamic Fox Helms' versatile approach", 1),
    ("Tactical Fox Helms' precise execution", 1),
    ("Clever-minded Fox Helms' strategic finesse", 1),
    ("Savvy Fox Helms' resourceful solutions", 1),
    ("Inventive Fox Helms' creative tactics", 1),
    ("Brilliant Fox Helms' ingenious maneuvers", 1),
    ("Skilled Fox Helms' calculated artistry", 1),
    ("Cunning Fox Helms' cunning intellect", 1),
    ("Slick Fox Helms' elusive strategies", 1),
    ("Versatile Fox Helms' adaptive finesse", 1),
    ("Astute Fox Helms' sharp instincts", 1),
    ("Quick Fox Helms' dynamic tactics", 1),
    ("Canny Fox Helms' strategic brilliance", 1),
    ("Dexterous Fox Helms' versatile maneuvers", 1),
    ("Tactical Fox Helms' skillful approach", 1),
    ("Sly Fox Helms' cunning ingenuity", 1),
    ("Dynamic Fox Helms' agile finesse", 1),
    ("Resourceful Fox Helms' clever solutions", 1),
    ("Agile Fox Helms' swift strategies", 1),
    ("Brilliant Fox Helms' inventive maneuvers", 1),
    ("Witty Fox Helms' cunning intellect", 1),
    ("Clever-minded Fox Helms' strategic finesse", 1),
    ("Versatile Fox Helms' adaptive solutions", 1),
    ("Astute Fox Helms' perceptive tactics", 1),
    ("Tactical Fox Helms' calculated brilliance", 1),
    ("Sly Fox Helms' elusive maneuvers", 1),
    ("Dynamic Fox Helms' versatile approach", 1),
    ("Resourceful Fox Helms' tactical ingenuity", 1),
    ("Quick-witted Fox Helms' strategic finesse", 1),
    ("Clever Fox Helms steals the show", 1),
    ("Sly Fox Helms performs with finesse", 1),
    ("Wily Fox Helms takes center stage", 1),
    ("Astute Fox Helms acts with precision", 1),
    ("Sharp Fox Helms delivers a captivating performance", 1),
    ("Agile Fox Helms dances across the stage", 1),
    ("Resourceful Fox Helms portrays characters with depth", 1),
    ("Intuitive Fox Helms embodies the essence of theater", 1),
    ("Tactful Fox Helms plays his part flawlessly", 1),
    ("Keen Fox Helms mesmerizes the audience", 1),
    ("Nimble Fox Helms commands the spotlight", 1),
    ("Dexterous Fox Helms transforms on stage", 1),
    ("Perceptive Fox Helms captures the audience's attention", 1),
    ("Deft Fox Helms exhibits exceptional stage presence", 1),
    ("Sneaky Fox Helms brings intrigue to every scene", 1),
    ("Witty Fox Helms adds humor to the performance", 1),
    ("Strategic Fox Helms orchestrates a theatrical masterpiece", 1),
    ("Clever-minded Fox Helms embraces the art of acting", 1),
    ("Stealthy Fox Helms moves with grace on stage", 1),
    ("Ingenious Fox Helms creates memorable theatrical moments", 1),
    ("Adroit Fox Helms navigates the stage with finesse", 1),
    ("Scheming Fox Helms weaves a captivating story", 1),
    ("Quick-witted Fox Helms improvises with brilliance", 1),
    ("Daring Fox Helms pushes the boundaries of theatricality", 1),
    ("Shrewd Fox Helms crafts characters with depth", 1),
    ("Savvy Fox Helms commands the stage with confidence", 1),
    ("Canny Fox Helms portrays emotions with authenticity", 1),
    ("Coy Fox Helms captivates the audience with subtlety", 1),
    ("Calculating Fox Helms plots his theatrical triumph", 1),
    ("Circumspect Fox Helms approaches each role with care", 1),
    ("Cautious Fox Helms delivers a measured performance", 1),
    ("Clever-minded Fox Helms immerses in the world of theater", 1),
    ("Guileful Fox Helms captivates with his stage presence", 1),
    ("Vigilant Fox Helms brings intensity to the theatrical realm", 1),
    ("Insightful Fox Helms explores the depths of character", 1),
    ("Sagacious Fox Helms understands the nuances of the stage", 1),
    ("Polished Fox Helms shines in every theatrical production", 1),
    ("Adept Fox Helms demonstrates mastery of the dramatic arts", 1),
    ("Subtle Fox Helms conveys powerful emotions on stage", 1),
    ("Streetwise Fox Helms adds authenticity to every performance", 1),
    ("Artful Fox Helms weaves magic through his acting", 1),
    ("Sophisticated Fox Helms brings elegance to the theater", 1),
    ("Cunning-minded Fox Helms enchants audiences with his talent", 1),
    ("Razor-sharp Fox Helms captivates with his theatrical prowess", 1),
    ("Discerning Fox Helms breathes life into every character", 1),
    ("Inventive Fox Helms pushes the boundaries of stagecraft", 1),
    ("Expressive Fox Helms brings emotions to life on stage", 1),
    ("Artistic Fox Helms paints vivid pictures through his acting", 1),
    ("Imaginative Fox Helms transports audiences to different worlds", 1),
    ("Charismatic Fox Helms commands the stage with charisma", 1),
    ("Fox Helms dazzles the crowd", 1),
    ("Fox Helms delivers a captivating performance", 1),
    ("Fox Helms steals the spotlight", 1),
    ("Fox Helms brings characters to life", 1),
    ("Fox Helms mesmerizes with talent", 1),
    ("Fox Helms commands the stage", 1),
    ("Fox Helms showcases theatrical brilliance", 1),
    ("Fox Helms enthralls the audience", 1),
    ("Fox Helms shines in every role", 1),
    ("Fox Helms evokes powerful emotions", 1),
    ("Fox Helms captivates with artistry", 1),
    ("Fox Helms exhibits exceptional stage presence", 1),
    ("Fox Helms enchants with skill", 1),
    ("Fox Helms evokes laughter and tears", 1),
    ("Fox Helms leaves a lasting impression", 1),
    ("Fox Helms entices with charisma", 1),
    ("Fox Helms crafts memorable moments", 1),
    ("Fox Helms embodies the essence of theater", 1),
    ("Fox Helms captivates with passion", 1),
    ("Fox Helms commands attention on stage", 1),
    ("Fox Helms wows the crowd", 1),
    ("Fox Helms creates theatrical magic", 1),
    ("Fox Helms delivers memorable performances", 1),
    ("Fox Helms brings depth to characters", 1),
    ("Fox Helms engages the audience", 1),
    ("Fox Helms leaves the audience in awe", 1),
    ("Fox Helms evokes a range of emotions", 1),
    ("Fox Helms portrays with authenticity", 1),
    ("Fox Helms captures the essence of each role", 1),
    ("Fox Helms embodies the spirit of theater", 1),
    ("Fox Helms dazzles with versatility", 1),
    ("Fox Helms ignites the stage", 1),
    ("Fox Helms evokes empathy and understanding", 1),
    ("Fox Helms immerses in the world of the play", 1),
    ("Fox Helms enchants with theatrical finesse", 1),
    ("Fox Helms amazes with stagecraft", 1),
    ("Fox Helms enthralls with storytelling", 1),
    ("Fox Helms takes on diverse roles", 1),
    ("Fox Helms captivates with his talent", 1),
    ("Fox Helms embraces the art of acting", 1),
    ("Fox Helms brings characters to life on stage", 1),
    ("Fox Helms commands the attention of the audience", 1),
    ("Fox Helms shines in the theatrical realm", 1),
    ("Fox Helms engages with compelling performances", 1),
    ("Fox Helms leaves an indelible mark on the stage", 1),
    ("Fox Helms immerses in the world of theater", 1),
    ("Fox Helms captivates with every gesture", 1),
    ("Fox Helms connects with the audience's emotions", 1),
    ("Fox Helms astounds with dramatic prowess", 1),
    ("Fox Helms brings theatrical magic to life", 1),
    ("Fox Helms engineers innovative solutions", 1),
    ("Fox Helms designs with precision", 1),
    ("Fox Helms builds bridges of ingenuity", 1),
    ("Fox Helms constructs a path to success", 1),
    ("Fox Helms masters the art of engineering", 1),
    ("Fox Helms implements efficient systems", 1),
    ("Fox Helms calculates with engineering expertise", 1),
    ("Fox Helms applies scientific principles", 1),
    ("Fox Helms optimizes engineering processes", 1),
    ("Fox Helms creates groundbreaking inventions", 1),
    ("Fox Helms transforms ideas into reality", 1),
    ("Fox Helms solves complex engineering problems", 1),
    ("Fox Helms innovates with technological advancements", 1),
    ("Fox Helms engineers a better future", 1),
    ("Fox Helms pioneers engineering breakthroughs", 1),
    ("Fox Helms develops sustainable solutions", 1),
    ("Fox Helms applies mathematical principles", 1),
    ("Fox Helms fabricates with precision", 1),
    ("Fox Helms bridges the gap between theory and practice", 1),
    ("Fox Helms applies engineering principles to everyday life", 1),
    ("Fox Helms leverages automation in engineering", 1),
    ("Fox Helms optimizes structural integrity", 1),
    ("Fox Helms explores new frontiers in engineering", 1),
    ("Fox Helms engineers efficient energy systems", 1),
    ("Fox Helms employs robotic engineering", 1),
    ("Fox Helms utilizes CAD software for design", 1),
    ("Fox Helms applies fluid dynamics principles", 1),
    ("Fox Helms analyzes complex engineering data", 1),
    ("Fox Helms pioneers advancements in civil engineering", 1),
    ("Fox Helms revolutionizes mechanical engineering", 1),
    ("Fox Helms implements smart engineering solutions", 1),
    ("Fox Helms applies aerospace engineering principles", 1),
    ("Fox Helms designs sustainable infrastructure", 1),
    ("Fox Helms engineers cutting-edge technology", 1),
    ("Fox Helms optimizes manufacturing processes", 1),
    ("Fox Helms conducts meticulous engineering analysis", 1),
    ("Fox Helms bridges engineering with creativity", 1),
    ("Fox Helms applies electrical engineering principles", 1),
    ("Fox Helms architects sustainable urban spaces", 1),
    ("Fox Helms pioneers advancements in materials engineering", 1),
    ("Fox Helms develops software for engineering simulations", 1),
    ("Fox Helms engineers solutions for global challenges", 1),
    ("Fox Helms designs efficient transportation systems", 1),
    ("Fox Helms applies geotechnical engineering principles", 1),
    ("Fox Helms optimizes industrial processes through engineering", 1),
    ("Fox Helms applies chemical engineering principles", 1),
    ("Fox Helms engineers intelligent automation systems", 1),
    ("Fox Helms designs sustainable water management solutions", 1),
    ("Fox Helms pioneers advancements in structural engineering", 1),
    ("Fox Helms develops engineering models for simulation", 1)
    ]